/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unchained.ServerBrowser.Model;
using Unchained.ServerBrowser.Client;
using System.Reflection;

namespace Unchained.ServerBrowser.Test.Model
{
    /// <summary>
    ///  Class for testing ApiPlayfabClientMatchmakePostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiPlayfabClientMatchmakePostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiPlayfabClientMatchmakePostRequest
        //private ApiPlayfabClientMatchmakePostRequest instance;

        public ApiPlayfabClientMatchmakePostRequestTests()
        {
            // TODO uncomment below to create an instance of ApiPlayfabClientMatchmakePostRequest
            //instance = new ApiPlayfabClientMatchmakePostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiPlayfabClientMatchmakePostRequest
        /// </summary>
        [Fact]
        public void ApiPlayfabClientMatchmakePostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiPlayfabClientMatchmakePostRequest
            //Assert.IsType<ApiPlayfabClientMatchmakePostRequest>(instance);
        }

        /// <summary>
        /// Test the property 'LobbyId'
        /// </summary>
        [Fact]
        public void LobbyIdTest()
        {
            // TODO unit test for the property 'LobbyId'
        }
    }
}
