/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unchained.ServerBrowser.Model;
using Unchained.ServerBrowser.Client;
using System.Reflection;

namespace Unchained.ServerBrowser.Test.Model
{
    /// <summary>
    ///  Class for testing BanListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BanListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BanListResponse
        //private BanListResponse instance;

        public BanListResponseTests()
        {
            // TODO uncomment below to create an instance of BanListResponse
            //instance = new BanListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BanListResponse
        /// </summary>
        [Fact]
        public void BanListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" BanListResponse
            //Assert.IsType<BanListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'BannedIps'
        /// </summary>
        [Fact]
        public void BannedIpsTest()
        {
            // TODO unit test for the property 'BannedIps'
        }
    }
}
