/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unchained.ServerBrowser.Model;
using Unchained.ServerBrowser.Client;
using System.Reflection;

namespace Unchained.ServerBrowser.Test.Model
{
    /// <summary>
    ///  Class for testing BanStatusResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BanStatusResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BanStatusResponse
        //private BanStatusResponse instance;

        public BanStatusResponseTests()
        {
            // TODO uncomment below to create an instance of BanStatusResponse
            //instance = new BanStatusResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BanStatusResponse
        /// </summary>
        [Fact]
        public void BanStatusResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" BanStatusResponse
            //Assert.IsType<BanStatusResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Banned'
        /// </summary>
        [Fact]
        public void BannedTest()
        {
            // TODO unit test for the property 'Banned'
        }
    }
}
