/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unchained.ServerBrowser.Model;
using Unchained.ServerBrowser.Client;
using System.Reflection;

namespace Unchained.ServerBrowser.Test.Model
{
    /// <summary>
    ///  Class for testing Chivalry2Ports
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Chivalry2PortsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Chivalry2Ports
        //private Chivalry2Ports instance;

        public Chivalry2PortsTests()
        {
            // TODO uncomment below to create an instance of Chivalry2Ports
            //instance = new Chivalry2Ports();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Chivalry2Ports
        /// </summary>
        [Fact]
        public void Chivalry2PortsInstanceTest()
        {
            // TODO uncomment below to test "IsType" Chivalry2Ports
            //Assert.IsType<Chivalry2Ports>(instance);
        }

        /// <summary>
        /// Test the property 'Game'
        /// </summary>
        [Fact]
        public void GameTest()
        {
            // TODO unit test for the property 'Game'
        }

        /// <summary>
        /// Test the property 'A2s'
        /// </summary>
        [Fact]
        public void A2sTest()
        {
            // TODO unit test for the property 'A2s'
        }

        /// <summary>
        /// Test the property 'Ping'
        /// </summary>
        [Fact]
        public void PingTest()
        {
            // TODO unit test for the property 'Ping'
        }
    }
}
