/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unchained.ServerBrowser.Model;
using Unchained.ServerBrowser.Client;
using System.Reflection;

namespace Unchained.ServerBrowser.Test.Model
{
    /// <summary>
    ///  Class for testing PlayfabGame
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PlayfabGameTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PlayfabGame
        //private PlayfabGame instance;

        public PlayfabGameTests()
        {
            // TODO uncomment below to create an instance of PlayfabGame
            //instance = new PlayfabGame();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PlayfabGame
        /// </summary>
        [Fact]
        public void PlayfabGameInstanceTest()
        {
            // TODO uncomment below to test "IsType" PlayfabGame
            //Assert.IsType<PlayfabGame>(instance);
        }

        /// <summary>
        /// Test the property 'ServerHostname'
        /// </summary>
        [Fact]
        public void ServerHostnameTest()
        {
            // TODO unit test for the property 'ServerHostname'
        }

        /// <summary>
        /// Test the property 'ServerIPV4Address'
        /// </summary>
        [Fact]
        public void ServerIPV4AddressTest()
        {
            // TODO unit test for the property 'ServerIPV4Address'
        }

        /// <summary>
        /// Test the property 'ServerPort'
        /// </summary>
        [Fact]
        public void ServerPortTest()
        {
            // TODO unit test for the property 'ServerPort'
        }

        /// <summary>
        /// Test the property 'Ticket'
        /// </summary>
        [Fact]
        public void TicketTest()
        {
            // TODO unit test for the property 'Ticket'
        }
    }
}
