/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unchained.ServerBrowser.Model;
using Unchained.ServerBrowser.Client;
using System.Reflection;

namespace Unchained.ServerBrowser.Test.Model
{
    /// <summary>
    ///  Class for testing PlayfabMatchmakeResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PlayfabMatchmakeResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PlayfabMatchmakeResponse
        //private PlayfabMatchmakeResponse instance;

        public PlayfabMatchmakeResponseTests()
        {
            // TODO uncomment below to create an instance of PlayfabMatchmakeResponse
            //instance = new PlayfabMatchmakeResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PlayfabMatchmakeResponse
        /// </summary>
        [Fact]
        public void PlayfabMatchmakeResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PlayfabMatchmakeResponse
            //Assert.IsType<PlayfabMatchmakeResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
