/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unchained.ServerBrowser.Model;
using Unchained.ServerBrowser.Client;
using System.Reflection;

namespace Unchained.ServerBrowser.Test.Model
{
    /// <summary>
    ///  Class for testing ServerResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServerResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServerResponse
        //private ServerResponse instance;

        public ServerResponseTests()
        {
            // TODO uncomment below to create an instance of ServerResponse
            //instance = new ServerResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServerResponse
        /// </summary>
        [Fact]
        public void ServerResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServerResponse
            //Assert.IsType<ServerResponse>(instance);
        }

        /// <summary>
        /// Test the property 'UniqueId'
        /// </summary>
        [Fact]
        public void UniqueIdTest()
        {
            // TODO unit test for the property 'UniqueId'
        }

        /// <summary>
        /// Test the property 'Ports'
        /// </summary>
        [Fact]
        public void PortsTest()
        {
            // TODO unit test for the property 'Ports'
        }

        /// <summary>
        /// Test the property 'PasswordProtected'
        /// </summary>
        [Fact]
        public void PasswordProtectedTest()
        {
            // TODO unit test for the property 'PasswordProtected'
        }

        /// <summary>
        /// Test the property 'IsVerified'
        /// </summary>
        [Fact]
        public void IsVerifiedTest()
        {
            // TODO unit test for the property 'IsVerified'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'CurrentMap'
        /// </summary>
        [Fact]
        public void CurrentMapTest()
        {
            // TODO unit test for the property 'CurrentMap'
        }

        /// <summary>
        /// Test the property 'PlayerCount'
        /// </summary>
        [Fact]
        public void PlayerCountTest()
        {
            // TODO unit test for the property 'PlayerCount'
        }

        /// <summary>
        /// Test the property 'MaxPlayers'
        /// </summary>
        [Fact]
        public void MaxPlayersTest()
        {
            // TODO unit test for the property 'MaxPlayers'
        }

        /// <summary>
        /// Test the property 'Mods'
        /// </summary>
        [Fact]
        public void ModsTest()
        {
            // TODO unit test for the property 'Mods'
        }

        /// <summary>
        /// Test the property 'LastHeartbeat'
        /// </summary>
        [Fact]
        public void LastHeartbeatTest()
        {
            // TODO unit test for the property 'LastHeartbeat'
        }
    }
}
