/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unchained.ServerBrowser.Model;
using Unchained.ServerBrowser.Client;
using System.Reflection;

namespace Unchained.ServerBrowser.Test.Model
{
    /// <summary>
    ///  Class for testing ServerListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServerListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServerListResponse
        //private ServerListResponse instance;

        public ServerListResponseTests()
        {
            // TODO uncomment below to create an instance of ServerListResponse
            //instance = new ServerListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServerListResponse
        /// </summary>
        [Fact]
        public void ServerListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServerListResponse
            //Assert.IsType<ServerListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Servers'
        /// </summary>
        [Fact]
        public void ServersTest()
        {
            // TODO unit test for the property 'Servers'
        }
    }
}
