/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unchained.ServerBrowser.Model;
using Unchained.ServerBrowser.Client;
using System.Reflection;

namespace Unchained.ServerBrowser.Test.Model
{
    /// <summary>
    ///  Class for testing TbioGame
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TbioGameTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TbioGame
        //private TbioGame instance;

        public TbioGameTests()
        {
            // TODO uncomment below to create an instance of TbioGame
            //instance = new TbioGame();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TbioGame
        /// </summary>
        [Fact]
        public void TbioGameInstanceTest()
        {
            // TODO uncomment below to test "IsType" TbioGame
            //Assert.IsType<TbioGame>(instance);
        }

        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }

        /// <summary>
        /// Test the property 'LobbyId'
        /// </summary>
        [Fact]
        public void LobbyIdTest()
        {
            // TODO unit test for the property 'LobbyId'
        }

        /// <summary>
        /// Test the property 'MaxPlayers'
        /// </summary>
        [Fact]
        public void MaxPlayersTest()
        {
            // TODO unit test for the property 'MaxPlayers'
        }

        /// <summary>
        /// Test the property 'Official'
        /// </summary>
        [Fact]
        public void OfficialTest()
        {
            // TODO unit test for the property 'Official'
        }

        /// <summary>
        /// Test the property 'BuildVersion'
        /// </summary>
        [Fact]
        public void BuildVersionTest()
        {
            // TODO unit test for the property 'BuildVersion'
        }

        /// <summary>
        /// Test the property 'GameMode'
        /// </summary>
        [Fact]
        public void GameModeTest()
        {
            // TODO unit test for the property 'GameMode'
        }

        /// <summary>
        /// Test the property 'PlayerUserIds'
        /// </summary>
        [Fact]
        public void PlayerUserIdsTest()
        {
            // TODO unit test for the property 'PlayerUserIds'
        }

        /// <summary>
        /// Test the property 'RunTime'
        /// </summary>
        [Fact]
        public void RunTimeTest()
        {
            // TODO unit test for the property 'RunTime'
        }

        /// <summary>
        /// Test the property 'GameServerState'
        /// </summary>
        [Fact]
        public void GameServerStateTest()
        {
            // TODO unit test for the property 'GameServerState'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

        /// <summary>
        /// Test the property 'LastHeartbeat'
        /// </summary>
        [Fact]
        public void LastHeartbeatTest()
        {
            // TODO unit test for the property 'LastHeartbeat'
        }

        /// <summary>
        /// Test the property 'ServerHostname'
        /// </summary>
        [Fact]
        public void ServerHostnameTest()
        {
            // TODO unit test for the property 'ServerHostname'
        }

        /// <summary>
        /// Test the property 'ServerIPV4Address'
        /// </summary>
        [Fact]
        public void ServerIPV4AddressTest()
        {
            // TODO unit test for the property 'ServerIPV4Address'
        }

        /// <summary>
        /// Test the property 'ServerPort'
        /// </summary>
        [Fact]
        public void ServerPortTest()
        {
            // TODO unit test for the property 'ServerPort'
        }
    }
}
