/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unchained.ServerBrowser.Model;
using Unchained.ServerBrowser.Client;
using System.Reflection;

namespace Unchained.ServerBrowser.Test.Model
{
    /// <summary>
    ///  Class for testing TbioTags
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TbioTagsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TbioTags
        //private TbioTags instance;

        public TbioTagsTests()
        {
            // TODO uncomment below to create an instance of TbioTags
            //instance = new TbioTags();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TbioTags
        /// </summary>
        [Fact]
        public void TbioTagsInstanceTest()
        {
            // TODO uncomment below to test "IsType" TbioTags
            //Assert.IsType<TbioTags>(instance);
        }

        /// <summary>
        /// Test the property 'BuildIdS'
        /// </summary>
        [Fact]
        public void BuildIdSTest()
        {
            // TODO unit test for the property 'BuildIdS'
        }

        /// <summary>
        /// Test the property 'ServerNameS'
        /// </summary>
        [Fact]
        public void ServerNameSTest()
        {
            // TODO unit test for the property 'ServerNameS'
        }

        /// <summary>
        /// Test the property 'RegionS'
        /// </summary>
        [Fact]
        public void RegionSTest()
        {
            // TODO unit test for the property 'RegionS'
        }

        /// <summary>
        /// Test the property 'OFFICIALB'
        /// </summary>
        [Fact]
        public void OFFICIALBTest()
        {
            // TODO unit test for the property 'OFFICIALB'
        }

        /// <summary>
        /// Test the property 'PlatformS'
        /// </summary>
        [Fact]
        public void PlatformSTest()
        {
            // TODO unit test for the property 'PlatformS'
        }

        /// <summary>
        /// Test the property 'FFAB'
        /// </summary>
        [Fact]
        public void FFABTest()
        {
            // TODO unit test for the property 'FFAB'
        }

        /// <summary>
        /// Test the property 'MSI'
        /// </summary>
        [Fact]
        public void MSITest()
        {
            // TODO unit test for the property 'MSI'
        }

        /// <summary>
        /// Test the property 'MapNameS'
        /// </summary>
        [Fact]
        public void MapNameSTest()
        {
            // TODO unit test for the property 'MapNameS'
        }

        /// <summary>
        /// Test the property 'PingPortI'
        /// </summary>
        [Fact]
        public void PingPortITest()
        {
            // TODO unit test for the property 'PingPortI'
        }

        /// <summary>
        /// Test the property 'QueryPortI'
        /// </summary>
        [Fact]
        public void QueryPortITest()
        {
            // TODO unit test for the property 'QueryPortI'
        }

        /// <summary>
        /// Test the property 'T0C'
        /// </summary>
        [Fact]
        public void T0CTest()
        {
            // TODO unit test for the property 'T0C'
        }

        /// <summary>
        /// Test the property 'PpB'
        /// </summary>
        [Fact]
        public void PpBTest()
        {
            // TODO unit test for the property 'PpB'
        }

        /// <summary>
        /// Test the property 'T1C'
        /// </summary>
        [Fact]
        public void T1CTest()
        {
            // TODO unit test for the property 'T1C'
        }

        /// <summary>
        /// Test the property 'MTIMI'
        /// </summary>
        [Fact]
        public void MTIMITest()
        {
            // TODO unit test for the property 'MTIMI'
        }
    }
}
