/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unchained.ServerBrowser.Model;
using Unchained.ServerBrowser.Client;
using System.Reflection;

namespace Unchained.ServerBrowser.Test.Model
{
    /// <summary>
    ///  Class for testing TbioServerListData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TbioServerListDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TbioServerListData
        //private TbioServerListData instance;

        public TbioServerListDataTests()
        {
            // TODO uncomment below to create an instance of TbioServerListData
            //instance = new TbioServerListData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TbioServerListData
        /// </summary>
        [Fact]
        public void TbioServerListDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" TbioServerListData
            //Assert.IsType<TbioServerListData>(instance);
        }

        /// <summary>
        /// Test the property 'GameCount'
        /// </summary>
        [Fact]
        public void GameCountTest()
        {
            // TODO unit test for the property 'GameCount'
        }

        /// <summary>
        /// Test the property 'PlayerCount'
        /// </summary>
        [Fact]
        public void PlayerCountTest()
        {
            // TODO unit test for the property 'PlayerCount'
        }

        /// <summary>
        /// Test the property 'Games'
        /// </summary>
        [Fact]
        public void GamesTest()
        {
            // TODO unit test for the property 'Games'
        }
    }
}
