/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unchained.ServerBrowser.Model;
using Unchained.ServerBrowser.Client;
using System.Reflection;

namespace Unchained.ServerBrowser.Test.Model
{
    /// <summary>
    ///  Class for testing TbioMotdResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TbioMotdResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TbioMotdResponse
        //private TbioMotdResponse instance;

        public TbioMotdResponseTests()
        {
            // TODO uncomment below to create an instance of TbioMotdResponse
            //instance = new TbioMotdResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TbioMotdResponse
        /// </summary>
        [Fact]
        public void TbioMotdResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TbioMotdResponse
            //Assert.IsType<TbioMotdResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Expiration'
        /// </summary>
        [Fact]
        public void ExpirationTest()
        {
            // TODO unit test for the property 'Expiration'
        }
    }
}
