/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unchained.ServerBrowser.Model;
using Unchained.ServerBrowser.Client;
using System.Reflection;

namespace Unchained.ServerBrowser.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateResponse
        //private UpdateResponse instance;

        public UpdateResponseTests()
        {
            // TODO uncomment below to create an instance of UpdateResponse
            //instance = new UpdateResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateResponse
        /// </summary>
        [Fact]
        public void UpdateResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateResponse
            //Assert.IsType<UpdateResponse>(instance);
        }

        /// <summary>
        /// Test the property 'RefreshBefore'
        /// </summary>
        [Fact]
        public void RefreshBeforeTest()
        {
            // TODO unit test for the property 'RefreshBefore'
        }

        /// <summary>
        /// Test the property 'Server'
        /// </summary>
        [Fact]
        public void ServerTest()
        {
            // TODO unit test for the property 'Server'
        }
    }
}
