/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unchained.ServerBrowser.Model;
using Unchained.ServerBrowser.Client;
using System.Reflection;

namespace Unchained.ServerBrowser.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateRegisteredServer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateRegisteredServerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateRegisteredServer
        //private UpdateRegisteredServer instance;

        public UpdateRegisteredServerTests()
        {
            // TODO uncomment below to create an instance of UpdateRegisteredServer
            //instance = new UpdateRegisteredServer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateRegisteredServer
        /// </summary>
        [Fact]
        public void UpdateRegisteredServerInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateRegisteredServer
            //Assert.IsType<UpdateRegisteredServer>(instance);
        }

        /// <summary>
        /// Test the property 'PlayerCount'
        /// </summary>
        [Fact]
        public void PlayerCountTest()
        {
            // TODO unit test for the property 'PlayerCount'
        }

        /// <summary>
        /// Test the property 'MaxPlayers'
        /// </summary>
        [Fact]
        public void MaxPlayersTest()
        {
            // TODO unit test for the property 'MaxPlayers'
        }

        /// <summary>
        /// Test the property 'CurrentMap'
        /// </summary>
        [Fact]
        public void CurrentMapTest()
        {
            // TODO unit test for the property 'CurrentMap'
        }
    }
}
