/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Unchained.ServerBrowser.Model;
using Unchained.ServerBrowser.Client;
using System.Reflection;

namespace Unchained.ServerBrowser.Test.Model
{
    /// <summary>
    ///  Class for testing VerifiedListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VerifiedListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VerifiedListResponse
        //private VerifiedListResponse instance;

        public VerifiedListResponseTests()
        {
            // TODO uncomment below to create an instance of VerifiedListResponse
            //instance = new VerifiedListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VerifiedListResponse
        /// </summary>
        [Fact]
        public void VerifiedListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" VerifiedListResponse
            //Assert.IsType<VerifiedListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'VerifiedIps'
        /// </summary>
        [Fact]
        public void VerifiedIpsTest()
        {
            // TODO unit test for the property 'VerifiedIps'
        }
    }
}
