/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;
using Unchained.ServerBrowser.Api;
using Unchained.ServerBrowser.Model;

namespace Unchained.ServerBrowser.Client
{
    /// <summary>
    /// Provides hosting configuration for Unchained.ServerBrowser
    /// </summary>
    public class HostConfiguration
    {
        private readonly IServiceCollection _services;
        private readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions();

        internal bool HttpClientsAdded { get; private set; }

        /// <summary>
        /// Instantiates the class 
        /// </summary>
        /// <param name="services"></param>
        public HostConfiguration(IServiceCollection services)
        {
            _services = services;
            _jsonOptions.Converters.Add(new JsonStringEnumConverter());
            _jsonOptions.Converters.Add(new DateTimeJsonConverter());
            _jsonOptions.Converters.Add(new DateTimeNullableJsonConverter());
            _jsonOptions.Converters.Add(new ApiPlayfabClientMatchmakePostRequestJsonConverter());
            _jsonOptions.Converters.Add(new BanListResponseJsonConverter());
            _jsonOptions.Converters.Add(new BanStatusResponseJsonConverter());
            _jsonOptions.Converters.Add(new Chivalry2PortsJsonConverter());
            _jsonOptions.Converters.Add(new ErrorResponseJsonConverter());
            _jsonOptions.Converters.Add(new IpListRequestJsonConverter());
            _jsonOptions.Converters.Add(new ModJsonConverter());
            _jsonOptions.Converters.Add(new MotdRequestJsonConverter());
            _jsonOptions.Converters.Add(new PlayfabErrorResponseJsonConverter());
            _jsonOptions.Converters.Add(new PlayfabGameJsonConverter());
            _jsonOptions.Converters.Add(new PlayfabMatchmakeResponseJsonConverter());
            _jsonOptions.Converters.Add(new RegistrationResponseJsonConverter());
            _jsonOptions.Converters.Add(new ServerListResponseJsonConverter());
            _jsonOptions.Converters.Add(new ServerRegistrationRequestJsonConverter());
            _jsonOptions.Converters.Add(new ServerResponseJsonConverter());
            _jsonOptions.Converters.Add(new StatusResponseJsonConverter());
            _jsonOptions.Converters.Add(new TbioGameJsonConverter());
            _jsonOptions.Converters.Add(new TbioMotdResponseJsonConverter());
            _jsonOptions.Converters.Add(new TbioServerListDataJsonConverter());
            _jsonOptions.Converters.Add(new TbioServerListResponseJsonConverter());
            _jsonOptions.Converters.Add(new TbioTagsJsonConverter());
            _jsonOptions.Converters.Add(new UpdateRegisteredServerJsonConverter());
            _jsonOptions.Converters.Add(new UpdateResponseJsonConverter());
            _jsonOptions.Converters.Add(new VerifiedListResponseJsonConverter());
            JsonSerializerOptionsProvider jsonSerializerOptionsProvider = new(_jsonOptions);
            _services.AddSingleton(jsonSerializerOptionsProvider);

            _jsonOptions.TypeInfoResolver = System.Text.Json.Serialization.Metadata.JsonTypeInfoResolver.Combine(
                new ApiPlayfabClientMatchmakePostRequestSerializationContext(),
                new BanListResponseSerializationContext(),
                new BanStatusResponseSerializationContext(),
                new Chivalry2PortsSerializationContext(),
                new ErrorResponseSerializationContext(),
                new IpListRequestSerializationContext(),
                new ModSerializationContext(),
                new MotdRequestSerializationContext(),
                new PlayfabErrorResponseSerializationContext(),
                new PlayfabGameSerializationContext(),
                new PlayfabMatchmakeResponseSerializationContext(),
                new RegistrationResponseSerializationContext(),
                new ServerListResponseSerializationContext(),
                new ServerRegistrationRequestSerializationContext(),
                new ServerResponseSerializationContext(),
                new StatusResponseSerializationContext(),
                new TbioGameSerializationContext(),
                new TbioMotdResponseSerializationContext(),
                new TbioServerListDataSerializationContext(),
                new TbioServerListResponseSerializationContext(),
                new TbioTagsSerializationContext(),
                new UpdateRegisteredServerSerializationContext(),
                new UpdateResponseSerializationContext(),
                new VerifiedListResponseSerializationContext(),
                new System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver()
            );

            _services.AddSingleton<IApiFactory, ApiFactory>();
            _services.AddSingleton<DefaultApiEvents>();
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="client"></param>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddServerBrowserAPIHttpClients
        (
            Action<HttpClient>? client = null, Action<IHttpClientBuilder>? builder = null)
        {
            if (client == null)
                client = c => c.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS);

            List<IHttpClientBuilder> builders = new List<IHttpClientBuilder>();

            builders.Add(_services.AddHttpClient<IDefaultApi, DefaultApi>(client));
            
            if (builder != null)
                foreach (IHttpClientBuilder instance in builders)
                    builder(instance);

            HttpClientsAdded = true;

            return this;
        }

        /// <summary>
        /// Configures the JsonSerializerSettings
        /// </summary>
        /// <param name="options"></param>
        /// <returns></returns>
        public HostConfiguration ConfigureJsonOptions(Action<JsonSerializerOptions> options)
        {
            options(_jsonOptions);

            return this;
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="token"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(TTokenBase token) where TTokenBase : TokenBase
        {
            return AddTokens(new TTokenBase[]{ token });
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="tokens"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(IEnumerable<TTokenBase> tokens) where TTokenBase : TokenBase
        {
            TokenContainer<TTokenBase> container = new TokenContainer<TTokenBase>(tokens);
            _services.AddSingleton(services => container);

            return this;
        }

        /// <summary>
        /// Adds a token provider to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenProvider"></typeparam>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <returns></returns>
        public HostConfiguration UseProvider<TTokenProvider, TTokenBase>() 
            where TTokenProvider : TokenProvider<TTokenBase>
            where TTokenBase : TokenBase
        {
            _services.AddSingleton<TTokenProvider>();
            _services.AddSingleton<TokenProvider<TTokenBase>>(services => services.GetRequiredService<TTokenProvider>());

            return this;
        }
    }
}
