/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Unchained.ServerBrowser.Api;
using Unchained.ServerBrowser.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Unchained.ServerBrowser.Test.Api
{
    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    public sealed class DefaultApiTests : ApiTestsBase
    {
        private readonly IDefaultApi _instance;

        public DefaultApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IDefaultApi>();
        }

        /// <summary>
        /// Test ApiPlayfabClientMatchmakePost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiPlayfabClientMatchmakePostAsyncTest()
        {
            Client.Option<ApiPlayfabClientMatchmakePostRequest> apiPlayfabClientMatchmakePostRequest = default!;
            var response = await _instance.ApiPlayfabClientMatchmakePostAsync(apiPlayfabClientMatchmakePostRequest);
            var model = response.BadRequest();
            Assert.IsType<PlayfabErrorResponse>(model);
        }

        /// <summary>
        /// Test ApiTbioGetCurrentGamesPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiTbioGetCurrentGamesPostAsyncTest()
        {
            var response = await _instance.ApiTbioGetCurrentGamesPostAsync();
            var model = response.Ok();
            Assert.IsType<TbioServerListResponse>(model);
        }

        /// <summary>
        /// Test ApiTbioGetMotdPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiTbioGetMotdPostAsyncTest()
        {
            Client.Option<MotdRequest> motdRequest = default!;
            var response = await _instance.ApiTbioGetMotdPostAsync(motdRequest);
            var model = response.Ok();
            Assert.IsType<TbioMotdResponse>(model);
        }

        /// <summary>
        /// Test ApiV1AdminBanListDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiV1AdminBanListDeleteAsyncTest()
        {
            string xCHIV2SERVERBROWSERADMINKEY = default!;
            IpListRequest ipListRequest = default!;
            var response = await _instance.ApiV1AdminBanListDeleteAsync(xCHIV2SERVERBROWSERADMINKEY, ipListRequest);
            var model = response.Forbidden();
            Assert.IsType<StatusResponse>(model);
        }

        /// <summary>
        /// Test ApiV1AdminBanListGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiV1AdminBanListGetAsyncTest()
        {
            string xCHIV2SERVERBROWSERADMINKEY = default!;
            var response = await _instance.ApiV1AdminBanListGetAsync(xCHIV2SERVERBROWSERADMINKEY);
            var model = response.Forbidden();
            Assert.IsType<StatusResponse>(model);
        }

        /// <summary>
        /// Test ApiV1AdminBanListPut
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiV1AdminBanListPutAsyncTest()
        {
            string xCHIV2SERVERBROWSERADMINKEY = default!;
            IpListRequest ipListRequest = default!;
            var response = await _instance.ApiV1AdminBanListPutAsync(xCHIV2SERVERBROWSERADMINKEY, ipListRequest);
            var model = response.BadRequest();
            Assert.IsType<StatusResponse>(model);
        }

        /// <summary>
        /// Test ApiV1AdminVerifiedListDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiV1AdminVerifiedListDeleteAsyncTest()
        {
            string xCHIV2SERVERBROWSERADMINKEY = default!;
            IpListRequest ipListRequest = default!;
            var response = await _instance.ApiV1AdminVerifiedListDeleteAsync(xCHIV2SERVERBROWSERADMINKEY, ipListRequest);
            var model = response.Forbidden();
            Assert.IsType<StatusResponse>(model);
        }

        /// <summary>
        /// Test ApiV1AdminVerifiedListGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiV1AdminVerifiedListGetAsyncTest()
        {
            string xCHIV2SERVERBROWSERADMINKEY = default!;
            var response = await _instance.ApiV1AdminVerifiedListGetAsync(xCHIV2SERVERBROWSERADMINKEY);
            var model = response.Forbidden();
            Assert.IsType<StatusResponse>(model);
        }

        /// <summary>
        /// Test ApiV1AdminVerifiedListPut
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiV1AdminVerifiedListPutAsyncTest()
        {
            string xCHIV2SERVERBROWSERADMINKEY = default!;
            IpListRequest ipListRequest = default!;
            var response = await _instance.ApiV1AdminVerifiedListPutAsync(xCHIV2SERVERBROWSERADMINKEY, ipListRequest);
            var model = response.BadRequest();
            Assert.IsType<StatusResponse>(model);
        }

        /// <summary>
        /// Test ApiV1CheckBannedIpGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiV1CheckBannedIpGetAsyncTest()
        {
            string ip = default!;
            var response = await _instance.ApiV1CheckBannedIpGetAsync(ip);
            var model = response.Ok();
            Assert.IsType<BanStatusResponse>(model);
        }

        /// <summary>
        /// Test ApiV1ServersGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiV1ServersGetAsyncTest()
        {
            var response = await _instance.ApiV1ServersGetAsync();
            var model = response.Ok();
            Assert.IsType<ServerListResponse>(model);
        }

        /// <summary>
        /// Test ApiV1ServersPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiV1ServersPostAsyncTest()
        {
            ServerRegistrationRequest serverRegistrationRequest = default!;
            var response = await _instance.ApiV1ServersPostAsync(serverRegistrationRequest);
            var model = response.Created();
            Assert.IsType<RegistrationResponse>(model);
        }

        /// <summary>
        /// Test ApiV1ServersUniqueIdDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiV1ServersUniqueIdDeleteAsyncTest()
        {
            string xCHIV2SERVERBROWSERKEY = default!;
            string uniqueId = default!;
            var response = await _instance.ApiV1ServersUniqueIdDeleteAsync(xCHIV2SERVERBROWSERKEY, uniqueId);
            var model = response.BadRequest();
            Assert.IsType<StatusResponse>(model);
        }

        /// <summary>
        /// Test ApiV1ServersUniqueIdHeartbeatPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiV1ServersUniqueIdHeartbeatPostAsyncTest()
        {
            string xCHIV2SERVERBROWSERKEY = default!;
            string uniqueId = default!;
            var response = await _instance.ApiV1ServersUniqueIdHeartbeatPostAsync(xCHIV2SERVERBROWSERKEY, uniqueId);
            var model = response.BadRequest();
            Assert.IsType<StatusResponse>(model);
        }

        /// <summary>
        /// Test ApiV1ServersUniqueIdPut
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiV1ServersUniqueIdPutAsyncTest()
        {
            string xCHIV2SERVERBROWSERKEY = default!;
            string uniqueId = default!;
            UpdateRegisteredServer updateRegisteredServer = default!;
            var response = await _instance.ApiV1ServersUniqueIdPutAsync(xCHIV2SERVERBROWSERKEY, uniqueId, updateRegisteredServer);
            var model = response.BadRequest();
            Assert.IsType<StatusResponse>(model);
        }

        /// <summary>
        /// Test ApiV1SwaggerYamlGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiV1SwaggerYamlGetAsyncTest()
        {
            var response = await _instance.ApiV1SwaggerYamlGetAsync();
            var model = response.Ok();
            Assert.IsType<string>(model);
        }
    }
}
