// <auto-generated>
/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Unchained.ServerBrowser.Client;

namespace Unchained.ServerBrowser.Model
{
    /// <summary>
    /// ApiPlayfabClientMatchmakePostRequest
    /// </summary>
    public partial class ApiPlayfabClientMatchmakePostRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiPlayfabClientMatchmakePostRequest" /> class.
        /// </summary>
        /// <param name="lobbyId">lobbyId</param>
        [JsonConstructor]
        public ApiPlayfabClientMatchmakePostRequest(string lobbyId)
        {
            LobbyId = lobbyId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets LobbyId
        /// </summary>
        [JsonPropertyName("LobbyId")]
        public string LobbyId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiPlayfabClientMatchmakePostRequest {\n");
            sb.Append("  LobbyId: ").Append(LobbyId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ApiPlayfabClientMatchmakePostRequest" />
    /// </summary>
    public class ApiPlayfabClientMatchmakePostRequestJsonConverter : JsonConverter<ApiPlayfabClientMatchmakePostRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="ApiPlayfabClientMatchmakePostRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ApiPlayfabClientMatchmakePostRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> lobbyId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "LobbyId":
                            lobbyId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!lobbyId.IsSet)
                throw new ArgumentException("Property is required for class ApiPlayfabClientMatchmakePostRequest.", nameof(lobbyId));

            if (lobbyId.IsSet && lobbyId.Value == null)
                throw new ArgumentNullException(nameof(lobbyId), "Property is not nullable for class ApiPlayfabClientMatchmakePostRequest.");

            return new ApiPlayfabClientMatchmakePostRequest(lobbyId.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ApiPlayfabClientMatchmakePostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiPlayfabClientMatchmakePostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ApiPlayfabClientMatchmakePostRequest apiPlayfabClientMatchmakePostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, apiPlayfabClientMatchmakePostRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ApiPlayfabClientMatchmakePostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiPlayfabClientMatchmakePostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ApiPlayfabClientMatchmakePostRequest apiPlayfabClientMatchmakePostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (apiPlayfabClientMatchmakePostRequest.LobbyId == null)
                throw new ArgumentNullException(nameof(apiPlayfabClientMatchmakePostRequest.LobbyId), "Property is required for class ApiPlayfabClientMatchmakePostRequest.");

            writer.WriteString("LobbyId", apiPlayfabClientMatchmakePostRequest.LobbyId);
        }
    }

    /// <summary>
    /// The ApiPlayfabClientMatchmakePostRequestSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(ApiPlayfabClientMatchmakePostRequest))]
    public partial class ApiPlayfabClientMatchmakePostRequestSerializationContext : JsonSerializerContext { }
}
