// <auto-generated>
/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Unchained.ServerBrowser.Client;

namespace Unchained.ServerBrowser.Model
{
    /// <summary>
    /// BanListResponse
    /// </summary>
    public partial class BanListResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BanListResponse" /> class.
        /// </summary>
        /// <param name="bannedIps">bannedIps</param>
        [JsonConstructor]
        public BanListResponse(List<string> bannedIps)
        {
            BannedIps = bannedIps;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets BannedIps
        /// </summary>
        [JsonPropertyName("banned_ips")]
        public List<string> BannedIps { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BanListResponse {\n");
            sb.Append("  BannedIps: ").Append(BannedIps).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BanListResponse" />
    /// </summary>
    public class BanListResponseJsonConverter : JsonConverter<BanListResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="BanListResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BanListResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<string>?> bannedIps = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "banned_ips":
                            bannedIps = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!bannedIps.IsSet)
                throw new ArgumentException("Property is required for class BanListResponse.", nameof(bannedIps));

            if (bannedIps.IsSet && bannedIps.Value == null)
                throw new ArgumentNullException(nameof(bannedIps), "Property is not nullable for class BanListResponse.");

            return new BanListResponse(bannedIps.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="BanListResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="banListResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BanListResponse banListResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, banListResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BanListResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="banListResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BanListResponse banListResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (banListResponse.BannedIps == null)
                throw new ArgumentNullException(nameof(banListResponse.BannedIps), "Property is required for class BanListResponse.");

            writer.WritePropertyName("banned_ips");
            JsonSerializer.Serialize(writer, banListResponse.BannedIps, jsonSerializerOptions);
        }
    }

    /// <summary>
    /// The BanListResponseSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(BanListResponse))]
    public partial class BanListResponseSerializationContext : JsonSerializerContext { }
}
