// <auto-generated>
/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Unchained.ServerBrowser.Client;

namespace Unchained.ServerBrowser.Model
{
    /// <summary>
    /// BanStatusResponse
    /// </summary>
    public partial class BanStatusResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BanStatusResponse" /> class.
        /// </summary>
        /// <param name="banned">Whether the IP is banned</param>
        [JsonConstructor]
        public BanStatusResponse(bool banned)
        {
            Banned = banned;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Whether the IP is banned
        /// </summary>
        /// <value>Whether the IP is banned</value>
        [JsonPropertyName("banned")]
        public bool Banned { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BanStatusResponse {\n");
            sb.Append("  Banned: ").Append(Banned).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BanStatusResponse" />
    /// </summary>
    public class BanStatusResponseJsonConverter : JsonConverter<BanStatusResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="BanStatusResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BanStatusResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> banned = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "banned":
                            banned = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!banned.IsSet)
                throw new ArgumentException("Property is required for class BanStatusResponse.", nameof(banned));

            if (banned.IsSet && banned.Value == null)
                throw new ArgumentNullException(nameof(banned), "Property is not nullable for class BanStatusResponse.");

            return new BanStatusResponse(banned.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="BanStatusResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="banStatusResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BanStatusResponse banStatusResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, banStatusResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BanStatusResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="banStatusResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BanStatusResponse banStatusResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteBoolean("banned", banStatusResponse.Banned);
        }
    }

    /// <summary>
    /// The BanStatusResponseSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(BanStatusResponse))]
    public partial class BanStatusResponseSerializationContext : JsonSerializerContext { }
}
