// <auto-generated>
/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Unchained.ServerBrowser.Client;

namespace Unchained.ServerBrowser.Model
{
    /// <summary>
    /// Chivalry2Ports
    /// </summary>
    public partial class Chivalry2Ports : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Chivalry2Ports" /> class.
        /// </summary>
        /// <param name="game">The port number the server is running on</param>
        /// <param name="a2s">The port number the server is responding to a2s requests at</param>
        /// <param name="ping">The port number the server is accepting ping requests at</param>
        [JsonConstructor]
        public Chivalry2Ports(int game, int a2s, int ping)
        {
            Game = game;
            A2s = a2s;
            Ping = ping;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The port number the server is running on
        /// </summary>
        /// <value>The port number the server is running on</value>
        [JsonPropertyName("game")]
        public int Game { get; set; }

        /// <summary>
        /// The port number the server is responding to a2s requests at
        /// </summary>
        /// <value>The port number the server is responding to a2s requests at</value>
        [JsonPropertyName("a2s")]
        public int A2s { get; set; }

        /// <summary>
        /// The port number the server is accepting ping requests at
        /// </summary>
        /// <value>The port number the server is accepting ping requests at</value>
        [JsonPropertyName("ping")]
        public int Ping { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Chivalry2Ports {\n");
            sb.Append("  Game: ").Append(Game).Append("\n");
            sb.Append("  A2s: ").Append(A2s).Append("\n");
            sb.Append("  Ping: ").Append(Ping).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Chivalry2Ports" />
    /// </summary>
    public class Chivalry2PortsJsonConverter : JsonConverter<Chivalry2Ports>
    {
        /// <summary>
        /// Deserializes json to <see cref="Chivalry2Ports" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Chivalry2Ports Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> game = default;
            Option<int?> a2s = default;
            Option<int?> ping = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "game":
                            game = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "a2s":
                            a2s = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "ping":
                            ping = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!game.IsSet)
                throw new ArgumentException("Property is required for class Chivalry2Ports.", nameof(game));

            if (!a2s.IsSet)
                throw new ArgumentException("Property is required for class Chivalry2Ports.", nameof(a2s));

            if (!ping.IsSet)
                throw new ArgumentException("Property is required for class Chivalry2Ports.", nameof(ping));

            if (game.IsSet && game.Value == null)
                throw new ArgumentNullException(nameof(game), "Property is not nullable for class Chivalry2Ports.");

            if (a2s.IsSet && a2s.Value == null)
                throw new ArgumentNullException(nameof(a2s), "Property is not nullable for class Chivalry2Ports.");

            if (ping.IsSet && ping.Value == null)
                throw new ArgumentNullException(nameof(ping), "Property is not nullable for class Chivalry2Ports.");

            return new Chivalry2Ports(game.Value!.Value!, a2s.Value!.Value!, ping.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="Chivalry2Ports" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="chivalry2Ports"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Chivalry2Ports chivalry2Ports, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, chivalry2Ports, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Chivalry2Ports" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="chivalry2Ports"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Chivalry2Ports chivalry2Ports, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("game", chivalry2Ports.Game);

            writer.WriteNumber("a2s", chivalry2Ports.A2s);

            writer.WriteNumber("ping", chivalry2Ports.Ping);
        }
    }

    /// <summary>
    /// The Chivalry2PortsSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(Chivalry2Ports))]
    public partial class Chivalry2PortsSerializationContext : JsonSerializerContext { }
}
