// <auto-generated>
/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Unchained.ServerBrowser.Client;

namespace Unchained.ServerBrowser.Model
{
    /// <summary>
    /// IpListRequest
    /// </summary>
    public partial class IpListRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IpListRequest" /> class.
        /// </summary>
        /// <param name="bannedIps">bannedIps</param>
        /// <param name="verifiedIps">verifiedIps</param>
        [JsonConstructor]
        public IpListRequest(Option<List<string>?> bannedIps = default, Option<List<string>?> verifiedIps = default)
        {
            BannedIpsOption = bannedIps;
            VerifiedIpsOption = verifiedIps;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of BannedIps
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> BannedIpsOption { get; private set; }

        /// <summary>
        /// Gets or Sets BannedIps
        /// </summary>
        [JsonPropertyName("banned_ips")]
        public List<string>? BannedIps { get { return this.BannedIpsOption; } set { this.BannedIpsOption = new(value); } }

        /// <summary>
        /// Used to track the state of VerifiedIps
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> VerifiedIpsOption { get; private set; }

        /// <summary>
        /// Gets or Sets VerifiedIps
        /// </summary>
        [JsonPropertyName("verified_ips")]
        public List<string>? VerifiedIps { get { return this.VerifiedIpsOption; } set { this.VerifiedIpsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IpListRequest {\n");
            sb.Append("  BannedIps: ").Append(BannedIps).Append("\n");
            sb.Append("  VerifiedIps: ").Append(VerifiedIps).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="IpListRequest" />
    /// </summary>
    public class IpListRequestJsonConverter : JsonConverter<IpListRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="IpListRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override IpListRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<string>?> bannedIps = default;
            Option<List<string>?> verifiedIps = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "banned_ips":
                            bannedIps = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "verified_ips":
                            verifiedIps = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (bannedIps.IsSet && bannedIps.Value == null)
                throw new ArgumentNullException(nameof(bannedIps), "Property is not nullable for class IpListRequest.");

            if (verifiedIps.IsSet && verifiedIps.Value == null)
                throw new ArgumentNullException(nameof(verifiedIps), "Property is not nullable for class IpListRequest.");

            return new IpListRequest(bannedIps, verifiedIps);
        }

        /// <summary>
        /// Serializes a <see cref="IpListRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ipListRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, IpListRequest ipListRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, ipListRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="IpListRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ipListRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, IpListRequest ipListRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (ipListRequest.BannedIpsOption.IsSet && ipListRequest.BannedIps == null)
                throw new ArgumentNullException(nameof(ipListRequest.BannedIps), "Property is required for class IpListRequest.");

            if (ipListRequest.VerifiedIpsOption.IsSet && ipListRequest.VerifiedIps == null)
                throw new ArgumentNullException(nameof(ipListRequest.VerifiedIps), "Property is required for class IpListRequest.");

            if (ipListRequest.BannedIpsOption.IsSet)
            {
                writer.WritePropertyName("banned_ips");
                JsonSerializer.Serialize(writer, ipListRequest.BannedIps, jsonSerializerOptions);
            }
            if (ipListRequest.VerifiedIpsOption.IsSet)
            {
                writer.WritePropertyName("verified_ips");
                JsonSerializer.Serialize(writer, ipListRequest.VerifiedIps, jsonSerializerOptions);
            }
        }
    }

    /// <summary>
    /// The IpListRequestSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(IpListRequest))]
    public partial class IpListRequestSerializationContext : JsonSerializerContext { }
}
