// <auto-generated>
/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Unchained.ServerBrowser.Client;

namespace Unchained.ServerBrowser.Model
{
    /// <summary>
    /// Mod
    /// </summary>
    public partial class Mod : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Mod" /> class.
        /// </summary>
        /// <param name="name">The name of the mod</param>
        /// <param name="organization">The organization that provides the mod</param>
        /// <param name="varVersion">The version of the mod</param>
        [JsonConstructor]
        public Mod(string name, string organization, string varVersion)
        {
            Name = name;
            Organization = organization;
            VarVersion = varVersion;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The name of the mod
        /// </summary>
        /// <value>The name of the mod</value>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// The organization that provides the mod
        /// </summary>
        /// <value>The organization that provides the mod</value>
        [JsonPropertyName("organization")]
        public string Organization { get; set; }

        /// <summary>
        /// The version of the mod
        /// </summary>
        /// <value>The version of the mod</value>
        [JsonPropertyName("version")]
        public string VarVersion { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Mod {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Organization: ").Append(Organization).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Mod" />
    /// </summary>
    public class ModJsonConverter : JsonConverter<Mod>
    {
        /// <summary>
        /// Deserializes json to <see cref="Mod" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Mod Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> organization = default;
            Option<string?> varVersion = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "organization":
                            organization = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "version":
                            varVersion = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class Mod.", nameof(name));

            if (!organization.IsSet)
                throw new ArgumentException("Property is required for class Mod.", nameof(organization));

            if (!varVersion.IsSet)
                throw new ArgumentException("Property is required for class Mod.", nameof(varVersion));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class Mod.");

            if (organization.IsSet && organization.Value == null)
                throw new ArgumentNullException(nameof(organization), "Property is not nullable for class Mod.");

            if (varVersion.IsSet && varVersion.Value == null)
                throw new ArgumentNullException(nameof(varVersion), "Property is not nullable for class Mod.");

            return new Mod(name.Value!, organization.Value!, varVersion.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="Mod" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mod"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Mod mod, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, mod, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Mod" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mod"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Mod mod, JsonSerializerOptions jsonSerializerOptions)
        {
            if (mod.Name == null)
                throw new ArgumentNullException(nameof(mod.Name), "Property is required for class Mod.");

            if (mod.Organization == null)
                throw new ArgumentNullException(nameof(mod.Organization), "Property is required for class Mod.");

            if (mod.VarVersion == null)
                throw new ArgumentNullException(nameof(mod.VarVersion), "Property is required for class Mod.");

            writer.WriteString("name", mod.Name);

            writer.WriteString("organization", mod.Organization);

            writer.WriteString("version", mod.VarVersion);
        }
    }

    /// <summary>
    /// The ModSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(Mod))]
    public partial class ModSerializationContext : JsonSerializerContext { }
}
