// <auto-generated>
/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Unchained.ServerBrowser.Client;

namespace Unchained.ServerBrowser.Model
{
    /// <summary>
    /// PlayfabGame
    /// </summary>
    public partial class PlayfabGame : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayfabGame" /> class.
        /// </summary>
        /// <param name="serverHostname">serverHostname</param>
        /// <param name="serverIPV4Address">serverIPV4Address</param>
        /// <param name="serverPort">serverPort</param>
        /// <param name="ticket">ticket</param>
        [JsonConstructor]
        public PlayfabGame(Option<string?> serverHostname = default, Option<string?> serverIPV4Address = default, Option<int?> serverPort = default, Option<string?> ticket = default)
        {
            ServerHostnameOption = serverHostname;
            ServerIPV4AddressOption = serverIPV4Address;
            ServerPortOption = serverPort;
            TicketOption = ticket;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of ServerHostname
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ServerHostnameOption { get; private set; }

        /// <summary>
        /// Gets or Sets ServerHostname
        /// </summary>
        [JsonPropertyName("ServerHostname")]
        public string? ServerHostname { get { return this.ServerHostnameOption; } set { this.ServerHostnameOption = new(value); } }

        /// <summary>
        /// Used to track the state of ServerIPV4Address
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ServerIPV4AddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets ServerIPV4Address
        /// </summary>
        [JsonPropertyName("ServerIPV4Address")]
        public string? ServerIPV4Address { get { return this.ServerIPV4AddressOption; } set { this.ServerIPV4AddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of ServerPort
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ServerPortOption { get; private set; }

        /// <summary>
        /// Gets or Sets ServerPort
        /// </summary>
        [JsonPropertyName("ServerPort")]
        public int? ServerPort { get { return this.ServerPortOption; } set { this.ServerPortOption = new(value); } }

        /// <summary>
        /// Used to track the state of Ticket
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TicketOption { get; private set; }

        /// <summary>
        /// Gets or Sets Ticket
        /// </summary>
        [JsonPropertyName("Ticket")]
        public string? Ticket { get { return this.TicketOption; } set { this.TicketOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlayfabGame {\n");
            sb.Append("  ServerHostname: ").Append(ServerHostname).Append("\n");
            sb.Append("  ServerIPV4Address: ").Append(ServerIPV4Address).Append("\n");
            sb.Append("  ServerPort: ").Append(ServerPort).Append("\n");
            sb.Append("  Ticket: ").Append(Ticket).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PlayfabGame" />
    /// </summary>
    public class PlayfabGameJsonConverter : JsonConverter<PlayfabGame>
    {
        /// <summary>
        /// Deserializes json to <see cref="PlayfabGame" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PlayfabGame Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> serverHostname = default;
            Option<string?> serverIPV4Address = default;
            Option<int?> serverPort = default;
            Option<string?> ticket = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "ServerHostname":
                            serverHostname = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "ServerIPV4Address":
                            serverIPV4Address = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "ServerPort":
                            serverPort = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Ticket":
                            ticket = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (serverHostname.IsSet && serverHostname.Value == null)
                throw new ArgumentNullException(nameof(serverHostname), "Property is not nullable for class PlayfabGame.");

            if (serverIPV4Address.IsSet && serverIPV4Address.Value == null)
                throw new ArgumentNullException(nameof(serverIPV4Address), "Property is not nullable for class PlayfabGame.");

            if (serverPort.IsSet && serverPort.Value == null)
                throw new ArgumentNullException(nameof(serverPort), "Property is not nullable for class PlayfabGame.");

            if (ticket.IsSet && ticket.Value == null)
                throw new ArgumentNullException(nameof(ticket), "Property is not nullable for class PlayfabGame.");

            return new PlayfabGame(serverHostname, serverIPV4Address, serverPort, ticket);
        }

        /// <summary>
        /// Serializes a <see cref="PlayfabGame" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="playfabGame"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PlayfabGame playfabGame, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, playfabGame, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PlayfabGame" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="playfabGame"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PlayfabGame playfabGame, JsonSerializerOptions jsonSerializerOptions)
        {
            if (playfabGame.ServerHostnameOption.IsSet && playfabGame.ServerHostname == null)
                throw new ArgumentNullException(nameof(playfabGame.ServerHostname), "Property is required for class PlayfabGame.");

            if (playfabGame.ServerIPV4AddressOption.IsSet && playfabGame.ServerIPV4Address == null)
                throw new ArgumentNullException(nameof(playfabGame.ServerIPV4Address), "Property is required for class PlayfabGame.");

            if (playfabGame.TicketOption.IsSet && playfabGame.Ticket == null)
                throw new ArgumentNullException(nameof(playfabGame.Ticket), "Property is required for class PlayfabGame.");

            if (playfabGame.ServerHostnameOption.IsSet)
                writer.WriteString("ServerHostname", playfabGame.ServerHostname);

            if (playfabGame.ServerIPV4AddressOption.IsSet)
                writer.WriteString("ServerIPV4Address", playfabGame.ServerIPV4Address);

            if (playfabGame.ServerPortOption.IsSet)
                writer.WriteNumber("ServerPort", playfabGame.ServerPortOption.Value!.Value);

            if (playfabGame.TicketOption.IsSet)
                writer.WriteString("Ticket", playfabGame.Ticket);
        }
    }

    /// <summary>
    /// The PlayfabGameSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(PlayfabGame))]
    public partial class PlayfabGameSerializationContext : JsonSerializerContext { }
}
