// <auto-generated>
/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Unchained.ServerBrowser.Client;

namespace Unchained.ServerBrowser.Model
{
    /// <summary>
    /// PlayfabMatchmakeResponse
    /// </summary>
    public partial class PlayfabMatchmakeResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayfabMatchmakeResponse" /> class.
        /// </summary>
        /// <param name="code">code</param>
        /// <param name="status">status</param>
        /// <param name="data">data</param>
        [JsonConstructor]
        public PlayfabMatchmakeResponse(Option<int?> code = default, Option<string?> status = default, Option<PlayfabGame?> data = default)
        {
            CodeOption = code;
            StatusOption = status;
            DataOption = data;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Code
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> CodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [JsonPropertyName("code")]
        public int? Code { get { return this.CodeOption; } set { this.CodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string? Status { get { return this.StatusOption; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Data
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<PlayfabGame?> DataOption { get; private set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [JsonPropertyName("data")]
        public PlayfabGame? Data { get { return this.DataOption; } set { this.DataOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlayfabMatchmakeResponse {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PlayfabMatchmakeResponse" />
    /// </summary>
    public class PlayfabMatchmakeResponseJsonConverter : JsonConverter<PlayfabMatchmakeResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="PlayfabMatchmakeResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PlayfabMatchmakeResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> code = default;
            Option<string?> status = default;
            Option<PlayfabGame?> data = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "code":
                            code = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "data":
                            data = new Option<PlayfabGame?>(JsonSerializer.Deserialize<PlayfabGame>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (code.IsSet && code.Value == null)
                throw new ArgumentNullException(nameof(code), "Property is not nullable for class PlayfabMatchmakeResponse.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class PlayfabMatchmakeResponse.");

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class PlayfabMatchmakeResponse.");

            return new PlayfabMatchmakeResponse(code, status, data);
        }

        /// <summary>
        /// Serializes a <see cref="PlayfabMatchmakeResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="playfabMatchmakeResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PlayfabMatchmakeResponse playfabMatchmakeResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, playfabMatchmakeResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PlayfabMatchmakeResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="playfabMatchmakeResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PlayfabMatchmakeResponse playfabMatchmakeResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (playfabMatchmakeResponse.StatusOption.IsSet && playfabMatchmakeResponse.Status == null)
                throw new ArgumentNullException(nameof(playfabMatchmakeResponse.Status), "Property is required for class PlayfabMatchmakeResponse.");

            if (playfabMatchmakeResponse.DataOption.IsSet && playfabMatchmakeResponse.Data == null)
                throw new ArgumentNullException(nameof(playfabMatchmakeResponse.Data), "Property is required for class PlayfabMatchmakeResponse.");

            if (playfabMatchmakeResponse.CodeOption.IsSet)
                writer.WriteNumber("code", playfabMatchmakeResponse.CodeOption.Value!.Value);

            if (playfabMatchmakeResponse.StatusOption.IsSet)
                writer.WriteString("status", playfabMatchmakeResponse.Status);

            if (playfabMatchmakeResponse.DataOption.IsSet)
            {
                writer.WritePropertyName("data");
                JsonSerializer.Serialize(writer, playfabMatchmakeResponse.Data, jsonSerializerOptions);
            }
        }
    }

    /// <summary>
    /// The PlayfabMatchmakeResponseSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(PlayfabMatchmakeResponse))]
    public partial class PlayfabMatchmakeResponseSerializationContext : JsonSerializerContext { }
}
