// <auto-generated>
/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Unchained.ServerBrowser.Client;

namespace Unchained.ServerBrowser.Model
{
    /// <summary>
    /// RegistrationResponse
    /// </summary>
    public partial class RegistrationResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RegistrationResponse" /> class.
        /// </summary>
        /// <param name="key">To be used as the X-CHIV2-SERVER-BROWSER-KEY header</param>
        /// <param name="refreshBefore">Unix timestamp for when the server should refresh its registration. Only present if operation was successful</param>
        /// <param name="server">server</param>
        [JsonConstructor]
        public RegistrationResponse(string key, double refreshBefore, ServerResponse server)
        {
            Key = key;
            RefreshBefore = refreshBefore;
            Server = server;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// To be used as the X-CHIV2-SERVER-BROWSER-KEY header
        /// </summary>
        /// <value>To be used as the X-CHIV2-SERVER-BROWSER-KEY header</value>
        [JsonPropertyName("key")]
        public string Key { get; set; }

        /// <summary>
        /// Unix timestamp for when the server should refresh its registration. Only present if operation was successful
        /// </summary>
        /// <value>Unix timestamp for when the server should refresh its registration. Only present if operation was successful</value>
        [JsonPropertyName("refresh_before")]
        public double RefreshBefore { get; set; }

        /// <summary>
        /// Gets or Sets Server
        /// </summary>
        [JsonPropertyName("server")]
        public ServerResponse Server { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RegistrationResponse {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  RefreshBefore: ").Append(RefreshBefore).Append("\n");
            sb.Append("  Server: ").Append(Server).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RegistrationResponse" />
    /// </summary>
    public class RegistrationResponseJsonConverter : JsonConverter<RegistrationResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="RegistrationResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RegistrationResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> key = default;
            Option<double?> refreshBefore = default;
            Option<ServerResponse?> server = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "key":
                            key = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "refresh_before":
                            refreshBefore = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "server":
                            server = new Option<ServerResponse?>(JsonSerializer.Deserialize<ServerResponse>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!key.IsSet)
                throw new ArgumentException("Property is required for class RegistrationResponse.", nameof(key));

            if (!refreshBefore.IsSet)
                throw new ArgumentException("Property is required for class RegistrationResponse.", nameof(refreshBefore));

            if (!server.IsSet)
                throw new ArgumentException("Property is required for class RegistrationResponse.", nameof(server));

            if (key.IsSet && key.Value == null)
                throw new ArgumentNullException(nameof(key), "Property is not nullable for class RegistrationResponse.");

            if (refreshBefore.IsSet && refreshBefore.Value == null)
                throw new ArgumentNullException(nameof(refreshBefore), "Property is not nullable for class RegistrationResponse.");

            if (server.IsSet && server.Value == null)
                throw new ArgumentNullException(nameof(server), "Property is not nullable for class RegistrationResponse.");

            return new RegistrationResponse(key.Value!, refreshBefore.Value!.Value!, server.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="RegistrationResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="registrationResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RegistrationResponse registrationResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, registrationResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RegistrationResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="registrationResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RegistrationResponse registrationResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (registrationResponse.Key == null)
                throw new ArgumentNullException(nameof(registrationResponse.Key), "Property is required for class RegistrationResponse.");

            if (registrationResponse.Server == null)
                throw new ArgumentNullException(nameof(registrationResponse.Server), "Property is required for class RegistrationResponse.");

            writer.WriteString("key", registrationResponse.Key);

            writer.WriteNumber("refresh_before", registrationResponse.RefreshBefore);

            writer.WritePropertyName("server");
            JsonSerializer.Serialize(writer, registrationResponse.Server, jsonSerializerOptions);
        }
    }

    /// <summary>
    /// The RegistrationResponseSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(RegistrationResponse))]
    public partial class RegistrationResponseSerializationContext : JsonSerializerContext { }
}
