// <auto-generated>
/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Unchained.ServerBrowser.Client;

namespace Unchained.ServerBrowser.Model
{
    /// <summary>
    /// ServerResponse
    /// </summary>
    public partial class ServerResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServerResponse" /> class.
        /// </summary>
        /// <param name="uniqueId">The unique identifier of this server</param>
        /// <param name="ports">ports</param>
        /// <param name="passwordProtected">Whether the server is password protected</param>
        /// <param name="isVerified">Whether the server is verified</param>
        /// <param name="name">The name of the server</param>
        /// <param name="description">A description of the server</param>
        /// <param name="currentMap">The current map being played on the server</param>
        /// <param name="playerCount">The number of players currently on the server</param>
        /// <param name="maxPlayers">The max number of players on the server</param>
        /// <param name="mods">A list of mods running on the server</param>
        /// <param name="lastHeartbeat">Unix timestamp of the last heartbeat</param>
        [JsonConstructor]
        public ServerResponse(string uniqueId, Chivalry2Ports ports, bool passwordProtected, bool isVerified, string name, string description, string currentMap, int playerCount, int maxPlayers, List<Mod> mods, double lastHeartbeat)
        {
            UniqueId = uniqueId;
            Ports = ports;
            PasswordProtected = passwordProtected;
            IsVerified = isVerified;
            Name = name;
            Description = description;
            CurrentMap = currentMap;
            PlayerCount = playerCount;
            MaxPlayers = maxPlayers;
            Mods = mods;
            LastHeartbeat = lastHeartbeat;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The unique identifier of this server
        /// </summary>
        /// <value>The unique identifier of this server</value>
        [JsonPropertyName("unique_id")]
        public string UniqueId { get; set; }

        /// <summary>
        /// Gets or Sets Ports
        /// </summary>
        [JsonPropertyName("ports")]
        public Chivalry2Ports Ports { get; set; }

        /// <summary>
        /// Whether the server is password protected
        /// </summary>
        /// <value>Whether the server is password protected</value>
        [JsonPropertyName("password_protected")]
        public bool PasswordProtected { get; set; }

        /// <summary>
        /// Whether the server is verified
        /// </summary>
        /// <value>Whether the server is verified</value>
        [JsonPropertyName("is_verified")]
        public bool IsVerified { get; set; }

        /// <summary>
        /// The name of the server
        /// </summary>
        /// <value>The name of the server</value>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// A description of the server
        /// </summary>
        /// <value>A description of the server</value>
        [JsonPropertyName("description")]
        public string Description { get; set; }

        /// <summary>
        /// The current map being played on the server
        /// </summary>
        /// <value>The current map being played on the server</value>
        [JsonPropertyName("current_map")]
        public string CurrentMap { get; set; }

        /// <summary>
        /// The number of players currently on the server
        /// </summary>
        /// <value>The number of players currently on the server</value>
        [JsonPropertyName("player_count")]
        public int PlayerCount { get; set; }

        /// <summary>
        /// The max number of players on the server
        /// </summary>
        /// <value>The max number of players on the server</value>
        [JsonPropertyName("max_players")]
        public int MaxPlayers { get; set; }

        /// <summary>
        /// A list of mods running on the server
        /// </summary>
        /// <value>A list of mods running on the server</value>
        [JsonPropertyName("mods")]
        public List<Mod> Mods { get; set; }

        /// <summary>
        /// Unix timestamp of the last heartbeat
        /// </summary>
        /// <value>Unix timestamp of the last heartbeat</value>
        [JsonPropertyName("last_heartbeat")]
        public double LastHeartbeat { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ServerResponse {\n");
            sb.Append("  UniqueId: ").Append(UniqueId).Append("\n");
            sb.Append("  Ports: ").Append(Ports).Append("\n");
            sb.Append("  PasswordProtected: ").Append(PasswordProtected).Append("\n");
            sb.Append("  IsVerified: ").Append(IsVerified).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  CurrentMap: ").Append(CurrentMap).Append("\n");
            sb.Append("  PlayerCount: ").Append(PlayerCount).Append("\n");
            sb.Append("  MaxPlayers: ").Append(MaxPlayers).Append("\n");
            sb.Append("  Mods: ").Append(Mods).Append("\n");
            sb.Append("  LastHeartbeat: ").Append(LastHeartbeat).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ServerResponse" />
    /// </summary>
    public class ServerResponseJsonConverter : JsonConverter<ServerResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="ServerResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ServerResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> uniqueId = default;
            Option<Chivalry2Ports?> ports = default;
            Option<bool?> passwordProtected = default;
            Option<bool?> isVerified = default;
            Option<string?> name = default;
            Option<string?> description = default;
            Option<string?> currentMap = default;
            Option<int?> playerCount = default;
            Option<int?> maxPlayers = default;
            Option<List<Mod>?> mods = default;
            Option<double?> lastHeartbeat = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "unique_id":
                            uniqueId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "ports":
                            ports = new Option<Chivalry2Ports?>(JsonSerializer.Deserialize<Chivalry2Ports>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "password_protected":
                            passwordProtected = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "is_verified":
                            isVerified = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "current_map":
                            currentMap = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "player_count":
                            playerCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "max_players":
                            maxPlayers = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "mods":
                            mods = new Option<List<Mod>?>(JsonSerializer.Deserialize<List<Mod>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "last_heartbeat":
                            lastHeartbeat = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!uniqueId.IsSet)
                throw new ArgumentException("Property is required for class ServerResponse.", nameof(uniqueId));

            if (!ports.IsSet)
                throw new ArgumentException("Property is required for class ServerResponse.", nameof(ports));

            if (!passwordProtected.IsSet)
                throw new ArgumentException("Property is required for class ServerResponse.", nameof(passwordProtected));

            if (!isVerified.IsSet)
                throw new ArgumentException("Property is required for class ServerResponse.", nameof(isVerified));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class ServerResponse.", nameof(name));

            if (!description.IsSet)
                throw new ArgumentException("Property is required for class ServerResponse.", nameof(description));

            if (!currentMap.IsSet)
                throw new ArgumentException("Property is required for class ServerResponse.", nameof(currentMap));

            if (!playerCount.IsSet)
                throw new ArgumentException("Property is required for class ServerResponse.", nameof(playerCount));

            if (!maxPlayers.IsSet)
                throw new ArgumentException("Property is required for class ServerResponse.", nameof(maxPlayers));

            if (!mods.IsSet)
                throw new ArgumentException("Property is required for class ServerResponse.", nameof(mods));

            if (!lastHeartbeat.IsSet)
                throw new ArgumentException("Property is required for class ServerResponse.", nameof(lastHeartbeat));

            if (uniqueId.IsSet && uniqueId.Value == null)
                throw new ArgumentNullException(nameof(uniqueId), "Property is not nullable for class ServerResponse.");

            if (ports.IsSet && ports.Value == null)
                throw new ArgumentNullException(nameof(ports), "Property is not nullable for class ServerResponse.");

            if (passwordProtected.IsSet && passwordProtected.Value == null)
                throw new ArgumentNullException(nameof(passwordProtected), "Property is not nullable for class ServerResponse.");

            if (isVerified.IsSet && isVerified.Value == null)
                throw new ArgumentNullException(nameof(isVerified), "Property is not nullable for class ServerResponse.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class ServerResponse.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class ServerResponse.");

            if (currentMap.IsSet && currentMap.Value == null)
                throw new ArgumentNullException(nameof(currentMap), "Property is not nullable for class ServerResponse.");

            if (playerCount.IsSet && playerCount.Value == null)
                throw new ArgumentNullException(nameof(playerCount), "Property is not nullable for class ServerResponse.");

            if (maxPlayers.IsSet && maxPlayers.Value == null)
                throw new ArgumentNullException(nameof(maxPlayers), "Property is not nullable for class ServerResponse.");

            if (mods.IsSet && mods.Value == null)
                throw new ArgumentNullException(nameof(mods), "Property is not nullable for class ServerResponse.");

            if (lastHeartbeat.IsSet && lastHeartbeat.Value == null)
                throw new ArgumentNullException(nameof(lastHeartbeat), "Property is not nullable for class ServerResponse.");

            return new ServerResponse(uniqueId.Value!, ports.Value!, passwordProtected.Value!.Value!, isVerified.Value!.Value!, name.Value!, description.Value!, currentMap.Value!, playerCount.Value!.Value!, maxPlayers.Value!.Value!, mods.Value!, lastHeartbeat.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ServerResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="serverResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ServerResponse serverResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, serverResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ServerResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="serverResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ServerResponse serverResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (serverResponse.UniqueId == null)
                throw new ArgumentNullException(nameof(serverResponse.UniqueId), "Property is required for class ServerResponse.");

            if (serverResponse.Ports == null)
                throw new ArgumentNullException(nameof(serverResponse.Ports), "Property is required for class ServerResponse.");

            if (serverResponse.Name == null)
                throw new ArgumentNullException(nameof(serverResponse.Name), "Property is required for class ServerResponse.");

            if (serverResponse.Description == null)
                throw new ArgumentNullException(nameof(serverResponse.Description), "Property is required for class ServerResponse.");

            if (serverResponse.CurrentMap == null)
                throw new ArgumentNullException(nameof(serverResponse.CurrentMap), "Property is required for class ServerResponse.");

            if (serverResponse.Mods == null)
                throw new ArgumentNullException(nameof(serverResponse.Mods), "Property is required for class ServerResponse.");

            writer.WriteString("unique_id", serverResponse.UniqueId);

            writer.WritePropertyName("ports");
            JsonSerializer.Serialize(writer, serverResponse.Ports, jsonSerializerOptions);
            writer.WriteBoolean("password_protected", serverResponse.PasswordProtected);

            writer.WriteBoolean("is_verified", serverResponse.IsVerified);

            writer.WriteString("name", serverResponse.Name);

            writer.WriteString("description", serverResponse.Description);

            writer.WriteString("current_map", serverResponse.CurrentMap);

            writer.WriteNumber("player_count", serverResponse.PlayerCount);

            writer.WriteNumber("max_players", serverResponse.MaxPlayers);

            writer.WritePropertyName("mods");
            JsonSerializer.Serialize(writer, serverResponse.Mods, jsonSerializerOptions);
            writer.WriteNumber("last_heartbeat", serverResponse.LastHeartbeat);
        }
    }

    /// <summary>
    /// The ServerResponseSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(ServerResponse))]
    public partial class ServerResponseSerializationContext : JsonSerializerContext { }
}
