// <auto-generated>
/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Unchained.ServerBrowser.Client;

namespace Unchained.ServerBrowser.Model
{
    /// <summary>
    /// ServerRegistrationRequest
    /// </summary>
    public partial class ServerRegistrationRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServerRegistrationRequest" /> class.
        /// </summary>
        /// <param name="ports">ports</param>
        /// <param name="name">The name of the server</param>
        /// <param name="description">A description of the server</param>
        /// <param name="currentMap">The current map being played on the server</param>
        /// <param name="playerCount">The number of players currently on the server</param>
        /// <param name="maxPlayers">The max number of players on the server</param>
        /// <param name="passwordProtected">Whether the server is password protected</param>
        /// <param name="mods">A list of mods running on the server</param>
        /// <param name="localIpAddress">The local IP address of the server</param>
        [JsonConstructor]
        public ServerRegistrationRequest(Chivalry2Ports ports, string name, string description, string currentMap, int playerCount, int maxPlayers, bool passwordProtected, List<Mod> mods, Option<string?> localIpAddress = default)
        {
            Ports = ports;
            Name = name;
            Description = description;
            CurrentMap = currentMap;
            PlayerCount = playerCount;
            MaxPlayers = maxPlayers;
            PasswordProtected = passwordProtected;
            Mods = mods;
            LocalIpAddressOption = localIpAddress;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Ports
        /// </summary>
        [JsonPropertyName("ports")]
        public Chivalry2Ports Ports { get; set; }

        /// <summary>
        /// The name of the server
        /// </summary>
        /// <value>The name of the server</value>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// A description of the server
        /// </summary>
        /// <value>A description of the server</value>
        [JsonPropertyName("description")]
        public string Description { get; set; }

        /// <summary>
        /// The current map being played on the server
        /// </summary>
        /// <value>The current map being played on the server</value>
        [JsonPropertyName("current_map")]
        public string CurrentMap { get; set; }

        /// <summary>
        /// The number of players currently on the server
        /// </summary>
        /// <value>The number of players currently on the server</value>
        [JsonPropertyName("player_count")]
        public int PlayerCount { get; set; }

        /// <summary>
        /// The max number of players on the server
        /// </summary>
        /// <value>The max number of players on the server</value>
        [JsonPropertyName("max_players")]
        public int MaxPlayers { get; set; }

        /// <summary>
        /// Whether the server is password protected
        /// </summary>
        /// <value>Whether the server is password protected</value>
        [JsonPropertyName("password_protected")]
        public bool PasswordProtected { get; set; }

        /// <summary>
        /// A list of mods running on the server
        /// </summary>
        /// <value>A list of mods running on the server</value>
        [JsonPropertyName("mods")]
        public List<Mod> Mods { get; set; }

        /// <summary>
        /// Used to track the state of LocalIpAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LocalIpAddressOption { get; private set; }

        /// <summary>
        /// The local IP address of the server
        /// </summary>
        /// <value>The local IP address of the server</value>
        [JsonPropertyName("local_ip_address")]
        public string? LocalIpAddress { get { return this.LocalIpAddressOption; } set { this.LocalIpAddressOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ServerRegistrationRequest {\n");
            sb.Append("  Ports: ").Append(Ports).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  CurrentMap: ").Append(CurrentMap).Append("\n");
            sb.Append("  PlayerCount: ").Append(PlayerCount).Append("\n");
            sb.Append("  MaxPlayers: ").Append(MaxPlayers).Append("\n");
            sb.Append("  PasswordProtected: ").Append(PasswordProtected).Append("\n");
            sb.Append("  Mods: ").Append(Mods).Append("\n");
            sb.Append("  LocalIpAddress: ").Append(LocalIpAddress).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ServerRegistrationRequest" />
    /// </summary>
    public class ServerRegistrationRequestJsonConverter : JsonConverter<ServerRegistrationRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="ServerRegistrationRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ServerRegistrationRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Chivalry2Ports?> ports = default;
            Option<string?> name = default;
            Option<string?> description = default;
            Option<string?> currentMap = default;
            Option<int?> playerCount = default;
            Option<int?> maxPlayers = default;
            Option<bool?> passwordProtected = default;
            Option<List<Mod>?> mods = default;
            Option<string?> localIpAddress = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "ports":
                            ports = new Option<Chivalry2Ports?>(JsonSerializer.Deserialize<Chivalry2Ports>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "current_map":
                            currentMap = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "player_count":
                            playerCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "max_players":
                            maxPlayers = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "password_protected":
                            passwordProtected = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "mods":
                            mods = new Option<List<Mod>?>(JsonSerializer.Deserialize<List<Mod>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "local_ip_address":
                            localIpAddress = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!ports.IsSet)
                throw new ArgumentException("Property is required for class ServerRegistrationRequest.", nameof(ports));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class ServerRegistrationRequest.", nameof(name));

            if (!description.IsSet)
                throw new ArgumentException("Property is required for class ServerRegistrationRequest.", nameof(description));

            if (!currentMap.IsSet)
                throw new ArgumentException("Property is required for class ServerRegistrationRequest.", nameof(currentMap));

            if (!playerCount.IsSet)
                throw new ArgumentException("Property is required for class ServerRegistrationRequest.", nameof(playerCount));

            if (!maxPlayers.IsSet)
                throw new ArgumentException("Property is required for class ServerRegistrationRequest.", nameof(maxPlayers));

            if (!passwordProtected.IsSet)
                throw new ArgumentException("Property is required for class ServerRegistrationRequest.", nameof(passwordProtected));

            if (!mods.IsSet)
                throw new ArgumentException("Property is required for class ServerRegistrationRequest.", nameof(mods));

            if (ports.IsSet && ports.Value == null)
                throw new ArgumentNullException(nameof(ports), "Property is not nullable for class ServerRegistrationRequest.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class ServerRegistrationRequest.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class ServerRegistrationRequest.");

            if (currentMap.IsSet && currentMap.Value == null)
                throw new ArgumentNullException(nameof(currentMap), "Property is not nullable for class ServerRegistrationRequest.");

            if (playerCount.IsSet && playerCount.Value == null)
                throw new ArgumentNullException(nameof(playerCount), "Property is not nullable for class ServerRegistrationRequest.");

            if (maxPlayers.IsSet && maxPlayers.Value == null)
                throw new ArgumentNullException(nameof(maxPlayers), "Property is not nullable for class ServerRegistrationRequest.");

            if (passwordProtected.IsSet && passwordProtected.Value == null)
                throw new ArgumentNullException(nameof(passwordProtected), "Property is not nullable for class ServerRegistrationRequest.");

            if (mods.IsSet && mods.Value == null)
                throw new ArgumentNullException(nameof(mods), "Property is not nullable for class ServerRegistrationRequest.");

            if (localIpAddress.IsSet && localIpAddress.Value == null)
                throw new ArgumentNullException(nameof(localIpAddress), "Property is not nullable for class ServerRegistrationRequest.");

            return new ServerRegistrationRequest(ports.Value!, name.Value!, description.Value!, currentMap.Value!, playerCount.Value!.Value!, maxPlayers.Value!.Value!, passwordProtected.Value!.Value!, mods.Value!, localIpAddress);
        }

        /// <summary>
        /// Serializes a <see cref="ServerRegistrationRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="serverRegistrationRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ServerRegistrationRequest serverRegistrationRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, serverRegistrationRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ServerRegistrationRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="serverRegistrationRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ServerRegistrationRequest serverRegistrationRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (serverRegistrationRequest.Ports == null)
                throw new ArgumentNullException(nameof(serverRegistrationRequest.Ports), "Property is required for class ServerRegistrationRequest.");

            if (serverRegistrationRequest.Name == null)
                throw new ArgumentNullException(nameof(serverRegistrationRequest.Name), "Property is required for class ServerRegistrationRequest.");

            if (serverRegistrationRequest.Description == null)
                throw new ArgumentNullException(nameof(serverRegistrationRequest.Description), "Property is required for class ServerRegistrationRequest.");

            if (serverRegistrationRequest.CurrentMap == null)
                throw new ArgumentNullException(nameof(serverRegistrationRequest.CurrentMap), "Property is required for class ServerRegistrationRequest.");

            if (serverRegistrationRequest.Mods == null)
                throw new ArgumentNullException(nameof(serverRegistrationRequest.Mods), "Property is required for class ServerRegistrationRequest.");

            if (serverRegistrationRequest.LocalIpAddressOption.IsSet && serverRegistrationRequest.LocalIpAddress == null)
                throw new ArgumentNullException(nameof(serverRegistrationRequest.LocalIpAddress), "Property is required for class ServerRegistrationRequest.");

            writer.WritePropertyName("ports");
            JsonSerializer.Serialize(writer, serverRegistrationRequest.Ports, jsonSerializerOptions);
            writer.WriteString("name", serverRegistrationRequest.Name);

            writer.WriteString("description", serverRegistrationRequest.Description);

            writer.WriteString("current_map", serverRegistrationRequest.CurrentMap);

            writer.WriteNumber("player_count", serverRegistrationRequest.PlayerCount);

            writer.WriteNumber("max_players", serverRegistrationRequest.MaxPlayers);

            writer.WriteBoolean("password_protected", serverRegistrationRequest.PasswordProtected);

            writer.WritePropertyName("mods");
            JsonSerializer.Serialize(writer, serverRegistrationRequest.Mods, jsonSerializerOptions);
            if (serverRegistrationRequest.LocalIpAddressOption.IsSet)
                writer.WriteString("local_ip_address", serverRegistrationRequest.LocalIpAddress);
        }
    }

    /// <summary>
    /// The ServerRegistrationRequestSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(ServerRegistrationRequest))]
    public partial class ServerRegistrationRequestSerializationContext : JsonSerializerContext { }
}
