// <auto-generated>
/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Unchained.ServerBrowser.Client;

namespace Unchained.ServerBrowser.Model
{
    /// <summary>
    /// StatusResponse
    /// </summary>
    public partial class StatusResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StatusResponse" /> class.
        /// </summary>
        /// <param name="status">The status code</param>
        /// <param name="message">A human readable message about the status</param>
        /// <param name="context">Optional context for the status</param>
        [JsonConstructor]
        public StatusResponse(string status, string message, Option<Object?> context = default)
        {
            Status = status;
            Message = message;
            ContextOption = context;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The status code
        /// </summary>
        /// <value>The status code</value>
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// A human readable message about the status
        /// </summary>
        /// <value>A human readable message about the status</value>
        [JsonPropertyName("message")]
        public string Message { get; set; }

        /// <summary>
        /// Used to track the state of Context
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> ContextOption { get; private set; }

        /// <summary>
        /// Optional context for the status
        /// </summary>
        /// <value>Optional context for the status</value>
        [JsonPropertyName("context")]
        public Object? Context { get { return this.ContextOption; } set { this.ContextOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StatusResponse {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Context: ").Append(Context).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="StatusResponse" />
    /// </summary>
    public class StatusResponseJsonConverter : JsonConverter<StatusResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="StatusResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override StatusResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> status = default;
            Option<string?> message = default;
            Option<Object?> context = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "context":
                            context = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class StatusResponse.", nameof(status));

            if (!message.IsSet)
                throw new ArgumentException("Property is required for class StatusResponse.", nameof(message));

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class StatusResponse.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class StatusResponse.");

            if (context.IsSet && context.Value == null)
                throw new ArgumentNullException(nameof(context), "Property is not nullable for class StatusResponse.");

            return new StatusResponse(status.Value!, message.Value!, context);
        }

        /// <summary>
        /// Serializes a <see cref="StatusResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="statusResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, StatusResponse statusResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, statusResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="StatusResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="statusResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, StatusResponse statusResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (statusResponse.Status == null)
                throw new ArgumentNullException(nameof(statusResponse.Status), "Property is required for class StatusResponse.");

            if (statusResponse.Message == null)
                throw new ArgumentNullException(nameof(statusResponse.Message), "Property is required for class StatusResponse.");

            if (statusResponse.ContextOption.IsSet && statusResponse.Context == null)
                throw new ArgumentNullException(nameof(statusResponse.Context), "Property is required for class StatusResponse.");

            writer.WriteString("status", statusResponse.Status);

            writer.WriteString("message", statusResponse.Message);

            if (statusResponse.ContextOption.IsSet)
            {
                writer.WritePropertyName("context");
                JsonSerializer.Serialize(writer, statusResponse.Context, jsonSerializerOptions);
            }
        }
    }

    /// <summary>
    /// The StatusResponseSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(StatusResponse))]
    public partial class StatusResponseSerializationContext : JsonSerializerContext { }
}
