// <auto-generated>
/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Unchained.ServerBrowser.Client;

namespace Unchained.ServerBrowser.Model
{
    /// <summary>
    /// TbioServerListResponse
    /// </summary>
    public partial class TbioServerListResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TbioServerListResponse" /> class.
        /// </summary>
        /// <param name="success">success</param>
        /// <param name="data">data</param>
        [JsonConstructor]
        public TbioServerListResponse(Option<bool?> success = default, Option<TbioServerListData?> data = default)
        {
            SuccessOption = success;
            DataOption = data;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Success
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SuccessOption { get; private set; }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [JsonPropertyName("Success")]
        public bool? Success { get { return this.SuccessOption; } set { this.SuccessOption = new(value); } }

        /// <summary>
        /// Used to track the state of Data
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TbioServerListData?> DataOption { get; private set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [JsonPropertyName("Data")]
        public TbioServerListData? Data { get { return this.DataOption; } set { this.DataOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TbioServerListResponse {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TbioServerListResponse" />
    /// </summary>
    public class TbioServerListResponseJsonConverter : JsonConverter<TbioServerListResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="TbioServerListResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TbioServerListResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> success = default;
            Option<TbioServerListData?> data = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "Success":
                            success = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Data":
                            data = new Option<TbioServerListData?>(JsonSerializer.Deserialize<TbioServerListData>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (success.IsSet && success.Value == null)
                throw new ArgumentNullException(nameof(success), "Property is not nullable for class TbioServerListResponse.");

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class TbioServerListResponse.");

            return new TbioServerListResponse(success, data);
        }

        /// <summary>
        /// Serializes a <see cref="TbioServerListResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tbioServerListResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TbioServerListResponse tbioServerListResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, tbioServerListResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TbioServerListResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tbioServerListResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TbioServerListResponse tbioServerListResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (tbioServerListResponse.DataOption.IsSet && tbioServerListResponse.Data == null)
                throw new ArgumentNullException(nameof(tbioServerListResponse.Data), "Property is required for class TbioServerListResponse.");

            if (tbioServerListResponse.SuccessOption.IsSet)
                writer.WriteBoolean("Success", tbioServerListResponse.SuccessOption.Value!.Value);

            if (tbioServerListResponse.DataOption.IsSet)
            {
                writer.WritePropertyName("Data");
                JsonSerializer.Serialize(writer, tbioServerListResponse.Data, jsonSerializerOptions);
            }
        }
    }

    /// <summary>
    /// The TbioServerListResponseSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(TbioServerListResponse))]
    public partial class TbioServerListResponseSerializationContext : JsonSerializerContext { }
}
