// <auto-generated>
/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Unchained.ServerBrowser.Client;

namespace Unchained.ServerBrowser.Model
{
    /// <summary>
    /// TbioTags
    /// </summary>
    public partial class TbioTags : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TbioTags" /> class.
        /// </summary>
        /// <param name="buildIdS">buildIdS</param>
        /// <param name="serverNameS">serverNameS</param>
        /// <param name="regionS">regionS</param>
        /// <param name="oFFICIALB">oFFICIALB</param>
        /// <param name="platformS">platformS</param>
        /// <param name="fFAB">fFAB</param>
        /// <param name="mSI">mSI</param>
        /// <param name="mapNameS">mapNameS</param>
        /// <param name="pingPortI">pingPortI</param>
        /// <param name="queryPortI">queryPortI</param>
        /// <param name="t0C">t0C</param>
        /// <param name="ppB">ppB</param>
        /// <param name="t1C">t1C</param>
        /// <param name="mTIMI">mTIMI</param>
        [JsonConstructor]
        public TbioTags(Option<string?> buildIdS = default, Option<string?> serverNameS = default, Option<string?> regionS = default, Option<string?> oFFICIALB = default, Option<string?> platformS = default, Option<string?> fFAB = default, Option<string?> mSI = default, Option<string?> mapNameS = default, Option<string?> pingPortI = default, Option<string?> queryPortI = default, Option<string?> t0C = default, Option<string?> ppB = default, Option<string?> t1C = default, Option<string?> mTIMI = default)
        {
            BuildIdSOption = buildIdS;
            ServerNameSOption = serverNameS;
            RegionSOption = regionS;
            OFFICIALBOption = oFFICIALB;
            PlatformSOption = platformS;
            FFABOption = fFAB;
            MSIOption = mSI;
            MapNameSOption = mapNameS;
            PingPortIOption = pingPortI;
            QueryPortIOption = queryPortI;
            T0COption = t0C;
            PpBOption = ppB;
            T1COption = t1C;
            MTIMIOption = mTIMI;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of BuildIdS
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BuildIdSOption { get; private set; }

        /// <summary>
        /// Gets or Sets BuildIdS
        /// </summary>
        [JsonPropertyName("BuildId_s")]
        public string? BuildIdS { get { return this.BuildIdSOption; } set { this.BuildIdSOption = new(value); } }

        /// <summary>
        /// Used to track the state of ServerNameS
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ServerNameSOption { get; private set; }

        /// <summary>
        /// Gets or Sets ServerNameS
        /// </summary>
        [JsonPropertyName("ServerName_s")]
        public string? ServerNameS { get { return this.ServerNameSOption; } set { this.ServerNameSOption = new(value); } }

        /// <summary>
        /// Used to track the state of RegionS
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RegionSOption { get; private set; }

        /// <summary>
        /// Gets or Sets RegionS
        /// </summary>
        [JsonPropertyName("Region_s")]
        public string? RegionS { get { return this.RegionSOption; } set { this.RegionSOption = new(value); } }

        /// <summary>
        /// Used to track the state of OFFICIALB
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OFFICIALBOption { get; private set; }

        /// <summary>
        /// Gets or Sets OFFICIALB
        /// </summary>
        [JsonPropertyName("OFFICIAL_b")]
        public string? OFFICIALB { get { return this.OFFICIALBOption; } set { this.OFFICIALBOption = new(value); } }

        /// <summary>
        /// Used to track the state of PlatformS
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PlatformSOption { get; private set; }

        /// <summary>
        /// Gets or Sets PlatformS
        /// </summary>
        [JsonPropertyName("Platform_s")]
        public string? PlatformS { get { return this.PlatformSOption; } set { this.PlatformSOption = new(value); } }

        /// <summary>
        /// Used to track the state of FFAB
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FFABOption { get; private set; }

        /// <summary>
        /// Gets or Sets FFAB
        /// </summary>
        [JsonPropertyName("FFA_b")]
        public string? FFAB { get { return this.FFABOption; } set { this.FFABOption = new(value); } }

        /// <summary>
        /// Used to track the state of MSI
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MSIOption { get; private set; }

        /// <summary>
        /// Gets or Sets MSI
        /// </summary>
        [JsonPropertyName("MS_i")]
        public string? MSI { get { return this.MSIOption; } set { this.MSIOption = new(value); } }

        /// <summary>
        /// Used to track the state of MapNameS
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MapNameSOption { get; private set; }

        /// <summary>
        /// Gets or Sets MapNameS
        /// </summary>
        [JsonPropertyName("MapName_s")]
        public string? MapNameS { get { return this.MapNameSOption; } set { this.MapNameSOption = new(value); } }

        /// <summary>
        /// Used to track the state of PingPortI
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PingPortIOption { get; private set; }

        /// <summary>
        /// Gets or Sets PingPortI
        /// </summary>
        [JsonPropertyName("PingPort_i")]
        public string? PingPortI { get { return this.PingPortIOption; } set { this.PingPortIOption = new(value); } }

        /// <summary>
        /// Used to track the state of QueryPortI
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> QueryPortIOption { get; private set; }

        /// <summary>
        /// Gets or Sets QueryPortI
        /// </summary>
        [JsonPropertyName("QueryPort_i")]
        public string? QueryPortI { get { return this.QueryPortIOption; } set { this.QueryPortIOption = new(value); } }

        /// <summary>
        /// Used to track the state of T0C
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> T0COption { get; private set; }

        /// <summary>
        /// Gets or Sets T0C
        /// </summary>
        [JsonPropertyName("T0_c")]
        public string? T0C { get { return this.T0COption; } set { this.T0COption = new(value); } }

        /// <summary>
        /// Used to track the state of PpB
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PpBOption { get; private set; }

        /// <summary>
        /// Gets or Sets PpB
        /// </summary>
        [JsonPropertyName("pp_b")]
        public string? PpB { get { return this.PpBOption; } set { this.PpBOption = new(value); } }

        /// <summary>
        /// Used to track the state of T1C
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> T1COption { get; private set; }

        /// <summary>
        /// Gets or Sets T1C
        /// </summary>
        [JsonPropertyName("t1_c")]
        public string? T1C { get { return this.T1COption; } set { this.T1COption = new(value); } }

        /// <summary>
        /// Used to track the state of MTIMI
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MTIMIOption { get; private set; }

        /// <summary>
        /// Gets or Sets MTIMI
        /// </summary>
        [JsonPropertyName("MTIM_i")]
        public string? MTIMI { get { return this.MTIMIOption; } set { this.MTIMIOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TbioTags {\n");
            sb.Append("  BuildIdS: ").Append(BuildIdS).Append("\n");
            sb.Append("  ServerNameS: ").Append(ServerNameS).Append("\n");
            sb.Append("  RegionS: ").Append(RegionS).Append("\n");
            sb.Append("  OFFICIALB: ").Append(OFFICIALB).Append("\n");
            sb.Append("  PlatformS: ").Append(PlatformS).Append("\n");
            sb.Append("  FFAB: ").Append(FFAB).Append("\n");
            sb.Append("  MSI: ").Append(MSI).Append("\n");
            sb.Append("  MapNameS: ").Append(MapNameS).Append("\n");
            sb.Append("  PingPortI: ").Append(PingPortI).Append("\n");
            sb.Append("  QueryPortI: ").Append(QueryPortI).Append("\n");
            sb.Append("  T0C: ").Append(T0C).Append("\n");
            sb.Append("  PpB: ").Append(PpB).Append("\n");
            sb.Append("  T1C: ").Append(T1C).Append("\n");
            sb.Append("  MTIMI: ").Append(MTIMI).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TbioTags" />
    /// </summary>
    public class TbioTagsJsonConverter : JsonConverter<TbioTags>
    {
        /// <summary>
        /// Deserializes json to <see cref="TbioTags" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TbioTags Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> buildIdS = default;
            Option<string?> serverNameS = default;
            Option<string?> regionS = default;
            Option<string?> oFFICIALB = default;
            Option<string?> platformS = default;
            Option<string?> fFAB = default;
            Option<string?> mSI = default;
            Option<string?> mapNameS = default;
            Option<string?> pingPortI = default;
            Option<string?> queryPortI = default;
            Option<string?> t0C = default;
            Option<string?> ppB = default;
            Option<string?> t1C = default;
            Option<string?> mTIMI = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "BuildId_s":
                            buildIdS = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "ServerName_s":
                            serverNameS = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "Region_s":
                            regionS = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "OFFICIAL_b":
                            oFFICIALB = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "Platform_s":
                            platformS = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "FFA_b":
                            fFAB = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "MS_i":
                            mSI = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "MapName_s":
                            mapNameS = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "PingPort_i":
                            pingPortI = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "QueryPort_i":
                            queryPortI = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "T0_c":
                            t0C = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "pp_b":
                            ppB = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "t1_c":
                            t1C = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "MTIM_i":
                            mTIMI = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (buildIdS.IsSet && buildIdS.Value == null)
                throw new ArgumentNullException(nameof(buildIdS), "Property is not nullable for class TbioTags.");

            if (serverNameS.IsSet && serverNameS.Value == null)
                throw new ArgumentNullException(nameof(serverNameS), "Property is not nullable for class TbioTags.");

            if (regionS.IsSet && regionS.Value == null)
                throw new ArgumentNullException(nameof(regionS), "Property is not nullable for class TbioTags.");

            if (oFFICIALB.IsSet && oFFICIALB.Value == null)
                throw new ArgumentNullException(nameof(oFFICIALB), "Property is not nullable for class TbioTags.");

            if (platformS.IsSet && platformS.Value == null)
                throw new ArgumentNullException(nameof(platformS), "Property is not nullable for class TbioTags.");

            if (fFAB.IsSet && fFAB.Value == null)
                throw new ArgumentNullException(nameof(fFAB), "Property is not nullable for class TbioTags.");

            if (mSI.IsSet && mSI.Value == null)
                throw new ArgumentNullException(nameof(mSI), "Property is not nullable for class TbioTags.");

            if (mapNameS.IsSet && mapNameS.Value == null)
                throw new ArgumentNullException(nameof(mapNameS), "Property is not nullable for class TbioTags.");

            if (pingPortI.IsSet && pingPortI.Value == null)
                throw new ArgumentNullException(nameof(pingPortI), "Property is not nullable for class TbioTags.");

            if (queryPortI.IsSet && queryPortI.Value == null)
                throw new ArgumentNullException(nameof(queryPortI), "Property is not nullable for class TbioTags.");

            if (t0C.IsSet && t0C.Value == null)
                throw new ArgumentNullException(nameof(t0C), "Property is not nullable for class TbioTags.");

            if (ppB.IsSet && ppB.Value == null)
                throw new ArgumentNullException(nameof(ppB), "Property is not nullable for class TbioTags.");

            if (t1C.IsSet && t1C.Value == null)
                throw new ArgumentNullException(nameof(t1C), "Property is not nullable for class TbioTags.");

            if (mTIMI.IsSet && mTIMI.Value == null)
                throw new ArgumentNullException(nameof(mTIMI), "Property is not nullable for class TbioTags.");

            return new TbioTags(buildIdS, serverNameS, regionS, oFFICIALB, platformS, fFAB, mSI, mapNameS, pingPortI, queryPortI, t0C, ppB, t1C, mTIMI);
        }

        /// <summary>
        /// Serializes a <see cref="TbioTags" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tbioTags"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TbioTags tbioTags, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, tbioTags, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TbioTags" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tbioTags"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TbioTags tbioTags, JsonSerializerOptions jsonSerializerOptions)
        {
            if (tbioTags.BuildIdSOption.IsSet && tbioTags.BuildIdS == null)
                throw new ArgumentNullException(nameof(tbioTags.BuildIdS), "Property is required for class TbioTags.");

            if (tbioTags.ServerNameSOption.IsSet && tbioTags.ServerNameS == null)
                throw new ArgumentNullException(nameof(tbioTags.ServerNameS), "Property is required for class TbioTags.");

            if (tbioTags.RegionSOption.IsSet && tbioTags.RegionS == null)
                throw new ArgumentNullException(nameof(tbioTags.RegionS), "Property is required for class TbioTags.");

            if (tbioTags.OFFICIALBOption.IsSet && tbioTags.OFFICIALB == null)
                throw new ArgumentNullException(nameof(tbioTags.OFFICIALB), "Property is required for class TbioTags.");

            if (tbioTags.PlatformSOption.IsSet && tbioTags.PlatformS == null)
                throw new ArgumentNullException(nameof(tbioTags.PlatformS), "Property is required for class TbioTags.");

            if (tbioTags.FFABOption.IsSet && tbioTags.FFAB == null)
                throw new ArgumentNullException(nameof(tbioTags.FFAB), "Property is required for class TbioTags.");

            if (tbioTags.MSIOption.IsSet && tbioTags.MSI == null)
                throw new ArgumentNullException(nameof(tbioTags.MSI), "Property is required for class TbioTags.");

            if (tbioTags.MapNameSOption.IsSet && tbioTags.MapNameS == null)
                throw new ArgumentNullException(nameof(tbioTags.MapNameS), "Property is required for class TbioTags.");

            if (tbioTags.PingPortIOption.IsSet && tbioTags.PingPortI == null)
                throw new ArgumentNullException(nameof(tbioTags.PingPortI), "Property is required for class TbioTags.");

            if (tbioTags.QueryPortIOption.IsSet && tbioTags.QueryPortI == null)
                throw new ArgumentNullException(nameof(tbioTags.QueryPortI), "Property is required for class TbioTags.");

            if (tbioTags.T0COption.IsSet && tbioTags.T0C == null)
                throw new ArgumentNullException(nameof(tbioTags.T0C), "Property is required for class TbioTags.");

            if (tbioTags.PpBOption.IsSet && tbioTags.PpB == null)
                throw new ArgumentNullException(nameof(tbioTags.PpB), "Property is required for class TbioTags.");

            if (tbioTags.T1COption.IsSet && tbioTags.T1C == null)
                throw new ArgumentNullException(nameof(tbioTags.T1C), "Property is required for class TbioTags.");

            if (tbioTags.MTIMIOption.IsSet && tbioTags.MTIMI == null)
                throw new ArgumentNullException(nameof(tbioTags.MTIMI), "Property is required for class TbioTags.");

            if (tbioTags.BuildIdSOption.IsSet)
                writer.WriteString("BuildId_s", tbioTags.BuildIdS);

            if (tbioTags.ServerNameSOption.IsSet)
                writer.WriteString("ServerName_s", tbioTags.ServerNameS);

            if (tbioTags.RegionSOption.IsSet)
                writer.WriteString("Region_s", tbioTags.RegionS);

            if (tbioTags.OFFICIALBOption.IsSet)
                writer.WriteString("OFFICIAL_b", tbioTags.OFFICIALB);

            if (tbioTags.PlatformSOption.IsSet)
                writer.WriteString("Platform_s", tbioTags.PlatformS);

            if (tbioTags.FFABOption.IsSet)
                writer.WriteString("FFA_b", tbioTags.FFAB);

            if (tbioTags.MSIOption.IsSet)
                writer.WriteString("MS_i", tbioTags.MSI);

            if (tbioTags.MapNameSOption.IsSet)
                writer.WriteString("MapName_s", tbioTags.MapNameS);

            if (tbioTags.PingPortIOption.IsSet)
                writer.WriteString("PingPort_i", tbioTags.PingPortI);

            if (tbioTags.QueryPortIOption.IsSet)
                writer.WriteString("QueryPort_i", tbioTags.QueryPortI);

            if (tbioTags.T0COption.IsSet)
                writer.WriteString("T0_c", tbioTags.T0C);

            if (tbioTags.PpBOption.IsSet)
                writer.WriteString("pp_b", tbioTags.PpB);

            if (tbioTags.T1COption.IsSet)
                writer.WriteString("t1_c", tbioTags.T1C);

            if (tbioTags.MTIMIOption.IsSet)
                writer.WriteString("MTIM_i", tbioTags.MTIMI);
        }
    }

    /// <summary>
    /// The TbioTagsSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(TbioTags))]
    public partial class TbioTagsSerializationContext : JsonSerializerContext { }
}
