// <auto-generated>
/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Unchained.ServerBrowser.Client;

namespace Unchained.ServerBrowser.Model
{
    /// <summary>
    /// TbioServerListData
    /// </summary>
    public partial class TbioServerListData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TbioServerListData" /> class.
        /// </summary>
        /// <param name="gameCount">gameCount</param>
        /// <param name="playerCount">playerCount</param>
        /// <param name="games">games</param>
        [JsonConstructor]
        public TbioServerListData(Option<int?> gameCount = default, Option<int?> playerCount = default, Option<List<TbioGame>?> games = default)
        {
            GameCountOption = gameCount;
            PlayerCountOption = playerCount;
            GamesOption = games;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of GameCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> GameCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets GameCount
        /// </summary>
        [JsonPropertyName("GameCount")]
        public int? GameCount { get { return this.GameCountOption; } set { this.GameCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of PlayerCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PlayerCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets PlayerCount
        /// </summary>
        [JsonPropertyName("PlayerCount")]
        public int? PlayerCount { get { return this.PlayerCountOption; } set { this.PlayerCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of Games
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<TbioGame>?> GamesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Games
        /// </summary>
        [JsonPropertyName("Games")]
        public List<TbioGame>? Games { get { return this.GamesOption; } set { this.GamesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TbioServerListData {\n");
            sb.Append("  GameCount: ").Append(GameCount).Append("\n");
            sb.Append("  PlayerCount: ").Append(PlayerCount).Append("\n");
            sb.Append("  Games: ").Append(Games).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TbioServerListData" />
    /// </summary>
    public class TbioServerListDataJsonConverter : JsonConverter<TbioServerListData>
    {
        /// <summary>
        /// Deserializes json to <see cref="TbioServerListData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TbioServerListData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> gameCount = default;
            Option<int?> playerCount = default;
            Option<List<TbioGame>?> games = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "GameCount":
                            gameCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "PlayerCount":
                            playerCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Games":
                            games = new Option<List<TbioGame>?>(JsonSerializer.Deserialize<List<TbioGame>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (gameCount.IsSet && gameCount.Value == null)
                throw new ArgumentNullException(nameof(gameCount), "Property is not nullable for class TbioServerListData.");

            if (playerCount.IsSet && playerCount.Value == null)
                throw new ArgumentNullException(nameof(playerCount), "Property is not nullable for class TbioServerListData.");

            if (games.IsSet && games.Value == null)
                throw new ArgumentNullException(nameof(games), "Property is not nullable for class TbioServerListData.");

            return new TbioServerListData(gameCount, playerCount, games);
        }

        /// <summary>
        /// Serializes a <see cref="TbioServerListData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tbioServerListData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TbioServerListData tbioServerListData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, tbioServerListData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TbioServerListData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tbioServerListData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TbioServerListData tbioServerListData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (tbioServerListData.GamesOption.IsSet && tbioServerListData.Games == null)
                throw new ArgumentNullException(nameof(tbioServerListData.Games), "Property is required for class TbioServerListData.");

            if (tbioServerListData.GameCountOption.IsSet)
                writer.WriteNumber("GameCount", tbioServerListData.GameCountOption.Value!.Value);

            if (tbioServerListData.PlayerCountOption.IsSet)
                writer.WriteNumber("PlayerCount", tbioServerListData.PlayerCountOption.Value!.Value);

            if (tbioServerListData.GamesOption.IsSet)
            {
                writer.WritePropertyName("Games");
                JsonSerializer.Serialize(writer, tbioServerListData.Games, jsonSerializerOptions);
            }
        }
    }

    /// <summary>
    /// The TbioServerListDataSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(TbioServerListData))]
    public partial class TbioServerListDataSerializationContext : JsonSerializerContext { }
}
