// <auto-generated>
/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Unchained.ServerBrowser.Client;

namespace Unchained.ServerBrowser.Model
{
    /// <summary>
    /// TbioGame
    /// </summary>
    public partial class TbioGame : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TbioGame" /> class.
        /// </summary>
        /// <param name="region">region</param>
        /// <param name="lobbyId">lobbyId</param>
        /// <param name="maxPlayers">maxPlayers</param>
        /// <param name="official">official</param>
        /// <param name="buildVersion">buildVersion</param>
        /// <param name="gameMode">gameMode</param>
        /// <param name="playerUserIds">playerUserIds</param>
        /// <param name="runTime">runTime</param>
        /// <param name="gameServerState">gameServerState</param>
        /// <param name="tags">tags</param>
        /// <param name="lastHeartbeat">lastHeartbeat</param>
        /// <param name="serverHostname">serverHostname</param>
        /// <param name="serverIPV4Address">serverIPV4Address</param>
        /// <param name="serverPort">serverPort</param>
        [JsonConstructor]
        public TbioGame(Option<string?> region = default, Option<string?> lobbyId = default, Option<int?> maxPlayers = default, Option<bool?> official = default, Option<string?> buildVersion = default, Option<string?> gameMode = default, Option<List<string>?> playerUserIds = default, Option<int?> runTime = default, Option<int?> gameServerState = default, Option<TbioTags?> tags = default, Option<int?> lastHeartbeat = default, Option<string?> serverHostname = default, Option<string?> serverIPV4Address = default, Option<int?> serverPort = default)
        {
            RegionOption = region;
            LobbyIdOption = lobbyId;
            MaxPlayersOption = maxPlayers;
            OfficialOption = official;
            BuildVersionOption = buildVersion;
            GameModeOption = gameMode;
            PlayerUserIdsOption = playerUserIds;
            RunTimeOption = runTime;
            GameServerStateOption = gameServerState;
            TagsOption = tags;
            LastHeartbeatOption = lastHeartbeat;
            ServerHostnameOption = serverHostname;
            ServerIPV4AddressOption = serverIPV4Address;
            ServerPortOption = serverPort;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Region
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RegionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Region
        /// </summary>
        [JsonPropertyName("Region")]
        public string? Region { get { return this.RegionOption; } set { this.RegionOption = new(value); } }

        /// <summary>
        /// Used to track the state of LobbyId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LobbyIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets LobbyId
        /// </summary>
        [JsonPropertyName("LobbyId")]
        public string? LobbyId { get { return this.LobbyIdOption; } set { this.LobbyIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of MaxPlayers
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> MaxPlayersOption { get; private set; }

        /// <summary>
        /// Gets or Sets MaxPlayers
        /// </summary>
        [JsonPropertyName("MaxPlayers")]
        public int? MaxPlayers { get { return this.MaxPlayersOption; } set { this.MaxPlayersOption = new(value); } }

        /// <summary>
        /// Used to track the state of Official
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> OfficialOption { get; private set; }

        /// <summary>
        /// Gets or Sets Official
        /// </summary>
        [JsonPropertyName("Official")]
        public bool? Official { get { return this.OfficialOption; } set { this.OfficialOption = new(value); } }

        /// <summary>
        /// Used to track the state of BuildVersion
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BuildVersionOption { get; private set; }

        /// <summary>
        /// Gets or Sets BuildVersion
        /// </summary>
        [JsonPropertyName("BuildVersion")]
        public string? BuildVersion { get { return this.BuildVersionOption; } set { this.BuildVersionOption = new(value); } }

        /// <summary>
        /// Used to track the state of GameMode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> GameModeOption { get; private set; }

        /// <summary>
        /// Gets or Sets GameMode
        /// </summary>
        [JsonPropertyName("GameMode")]
        public string? GameMode { get { return this.GameModeOption; } set { this.GameModeOption = new(value); } }

        /// <summary>
        /// Used to track the state of PlayerUserIds
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> PlayerUserIdsOption { get; private set; }

        /// <summary>
        /// Gets or Sets PlayerUserIds
        /// </summary>
        [JsonPropertyName("PlayerUserIds")]
        public List<string>? PlayerUserIds { get { return this.PlayerUserIdsOption; } set { this.PlayerUserIdsOption = new(value); } }

        /// <summary>
        /// Used to track the state of RunTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> RunTimeOption { get; private set; }

        /// <summary>
        /// Gets or Sets RunTime
        /// </summary>
        [JsonPropertyName("RunTime")]
        public int? RunTime { get { return this.RunTimeOption; } set { this.RunTimeOption = new(value); } }

        /// <summary>
        /// Used to track the state of GameServerState
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> GameServerStateOption { get; private set; }

        /// <summary>
        /// Gets or Sets GameServerState
        /// </summary>
        [JsonPropertyName("GameServerState")]
        public int? GameServerState { get { return this.GameServerStateOption; } set { this.GameServerStateOption = new(value); } }

        /// <summary>
        /// Used to track the state of Tags
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TbioTags?> TagsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [JsonPropertyName("Tags")]
        public TbioTags? Tags { get { return this.TagsOption; } set { this.TagsOption = new(value); } }

        /// <summary>
        /// Used to track the state of LastHeartbeat
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> LastHeartbeatOption { get; private set; }

        /// <summary>
        /// Gets or Sets LastHeartbeat
        /// </summary>
        [JsonPropertyName("LastHeartbeat")]
        public int? LastHeartbeat { get { return this.LastHeartbeatOption; } set { this.LastHeartbeatOption = new(value); } }

        /// <summary>
        /// Used to track the state of ServerHostname
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ServerHostnameOption { get; private set; }

        /// <summary>
        /// Gets or Sets ServerHostname
        /// </summary>
        [JsonPropertyName("ServerHostname")]
        public string? ServerHostname { get { return this.ServerHostnameOption; } set { this.ServerHostnameOption = new(value); } }

        /// <summary>
        /// Used to track the state of ServerIPV4Address
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ServerIPV4AddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets ServerIPV4Address
        /// </summary>
        [JsonPropertyName("ServerIPV4Address")]
        public string? ServerIPV4Address { get { return this.ServerIPV4AddressOption; } set { this.ServerIPV4AddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of ServerPort
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ServerPortOption { get; private set; }

        /// <summary>
        /// Gets or Sets ServerPort
        /// </summary>
        [JsonPropertyName("ServerPort")]
        public int? ServerPort { get { return this.ServerPortOption; } set { this.ServerPortOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TbioGame {\n");
            sb.Append("  Region: ").Append(Region).Append("\n");
            sb.Append("  LobbyId: ").Append(LobbyId).Append("\n");
            sb.Append("  MaxPlayers: ").Append(MaxPlayers).Append("\n");
            sb.Append("  Official: ").Append(Official).Append("\n");
            sb.Append("  BuildVersion: ").Append(BuildVersion).Append("\n");
            sb.Append("  GameMode: ").Append(GameMode).Append("\n");
            sb.Append("  PlayerUserIds: ").Append(PlayerUserIds).Append("\n");
            sb.Append("  RunTime: ").Append(RunTime).Append("\n");
            sb.Append("  GameServerState: ").Append(GameServerState).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  LastHeartbeat: ").Append(LastHeartbeat).Append("\n");
            sb.Append("  ServerHostname: ").Append(ServerHostname).Append("\n");
            sb.Append("  ServerIPV4Address: ").Append(ServerIPV4Address).Append("\n");
            sb.Append("  ServerPort: ").Append(ServerPort).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TbioGame" />
    /// </summary>
    public class TbioGameJsonConverter : JsonConverter<TbioGame>
    {
        /// <summary>
        /// Deserializes json to <see cref="TbioGame" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TbioGame Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> region = default;
            Option<string?> lobbyId = default;
            Option<int?> maxPlayers = default;
            Option<bool?> official = default;
            Option<string?> buildVersion = default;
            Option<string?> gameMode = default;
            Option<List<string>?> playerUserIds = default;
            Option<int?> runTime = default;
            Option<int?> gameServerState = default;
            Option<TbioTags?> tags = default;
            Option<int?> lastHeartbeat = default;
            Option<string?> serverHostname = default;
            Option<string?> serverIPV4Address = default;
            Option<int?> serverPort = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "Region":
                            region = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "LobbyId":
                            lobbyId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "MaxPlayers":
                            maxPlayers = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Official":
                            official = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "BuildVersion":
                            buildVersion = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "GameMode":
                            gameMode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "PlayerUserIds":
                            playerUserIds = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "RunTime":
                            runTime = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "GameServerState":
                            gameServerState = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "Tags":
                            tags = new Option<TbioTags?>(JsonSerializer.Deserialize<TbioTags>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "LastHeartbeat":
                            lastHeartbeat = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "ServerHostname":
                            serverHostname = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "ServerIPV4Address":
                            serverIPV4Address = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "ServerPort":
                            serverPort = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (region.IsSet && region.Value == null)
                throw new ArgumentNullException(nameof(region), "Property is not nullable for class TbioGame.");

            if (lobbyId.IsSet && lobbyId.Value == null)
                throw new ArgumentNullException(nameof(lobbyId), "Property is not nullable for class TbioGame.");

            if (maxPlayers.IsSet && maxPlayers.Value == null)
                throw new ArgumentNullException(nameof(maxPlayers), "Property is not nullable for class TbioGame.");

            if (official.IsSet && official.Value == null)
                throw new ArgumentNullException(nameof(official), "Property is not nullable for class TbioGame.");

            if (buildVersion.IsSet && buildVersion.Value == null)
                throw new ArgumentNullException(nameof(buildVersion), "Property is not nullable for class TbioGame.");

            if (gameMode.IsSet && gameMode.Value == null)
                throw new ArgumentNullException(nameof(gameMode), "Property is not nullable for class TbioGame.");

            if (playerUserIds.IsSet && playerUserIds.Value == null)
                throw new ArgumentNullException(nameof(playerUserIds), "Property is not nullable for class TbioGame.");

            if (runTime.IsSet && runTime.Value == null)
                throw new ArgumentNullException(nameof(runTime), "Property is not nullable for class TbioGame.");

            if (gameServerState.IsSet && gameServerState.Value == null)
                throw new ArgumentNullException(nameof(gameServerState), "Property is not nullable for class TbioGame.");

            if (tags.IsSet && tags.Value == null)
                throw new ArgumentNullException(nameof(tags), "Property is not nullable for class TbioGame.");

            if (lastHeartbeat.IsSet && lastHeartbeat.Value == null)
                throw new ArgumentNullException(nameof(lastHeartbeat), "Property is not nullable for class TbioGame.");

            if (serverHostname.IsSet && serverHostname.Value == null)
                throw new ArgumentNullException(nameof(serverHostname), "Property is not nullable for class TbioGame.");

            if (serverIPV4Address.IsSet && serverIPV4Address.Value == null)
                throw new ArgumentNullException(nameof(serverIPV4Address), "Property is not nullable for class TbioGame.");

            if (serverPort.IsSet && serverPort.Value == null)
                throw new ArgumentNullException(nameof(serverPort), "Property is not nullable for class TbioGame.");

            return new TbioGame(region, lobbyId, maxPlayers, official, buildVersion, gameMode, playerUserIds, runTime, gameServerState, tags, lastHeartbeat, serverHostname, serverIPV4Address, serverPort);
        }

        /// <summary>
        /// Serializes a <see cref="TbioGame" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tbioGame"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TbioGame tbioGame, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, tbioGame, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TbioGame" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tbioGame"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TbioGame tbioGame, JsonSerializerOptions jsonSerializerOptions)
        {
            if (tbioGame.RegionOption.IsSet && tbioGame.Region == null)
                throw new ArgumentNullException(nameof(tbioGame.Region), "Property is required for class TbioGame.");

            if (tbioGame.LobbyIdOption.IsSet && tbioGame.LobbyId == null)
                throw new ArgumentNullException(nameof(tbioGame.LobbyId), "Property is required for class TbioGame.");

            if (tbioGame.BuildVersionOption.IsSet && tbioGame.BuildVersion == null)
                throw new ArgumentNullException(nameof(tbioGame.BuildVersion), "Property is required for class TbioGame.");

            if (tbioGame.GameModeOption.IsSet && tbioGame.GameMode == null)
                throw new ArgumentNullException(nameof(tbioGame.GameMode), "Property is required for class TbioGame.");

            if (tbioGame.PlayerUserIdsOption.IsSet && tbioGame.PlayerUserIds == null)
                throw new ArgumentNullException(nameof(tbioGame.PlayerUserIds), "Property is required for class TbioGame.");

            if (tbioGame.TagsOption.IsSet && tbioGame.Tags == null)
                throw new ArgumentNullException(nameof(tbioGame.Tags), "Property is required for class TbioGame.");

            if (tbioGame.ServerHostnameOption.IsSet && tbioGame.ServerHostname == null)
                throw new ArgumentNullException(nameof(tbioGame.ServerHostname), "Property is required for class TbioGame.");

            if (tbioGame.ServerIPV4AddressOption.IsSet && tbioGame.ServerIPV4Address == null)
                throw new ArgumentNullException(nameof(tbioGame.ServerIPV4Address), "Property is required for class TbioGame.");

            if (tbioGame.RegionOption.IsSet)
                writer.WriteString("Region", tbioGame.Region);

            if (tbioGame.LobbyIdOption.IsSet)
                writer.WriteString("LobbyId", tbioGame.LobbyId);

            if (tbioGame.MaxPlayersOption.IsSet)
                writer.WriteNumber("MaxPlayers", tbioGame.MaxPlayersOption.Value!.Value);

            if (tbioGame.OfficialOption.IsSet)
                writer.WriteBoolean("Official", tbioGame.OfficialOption.Value!.Value);

            if (tbioGame.BuildVersionOption.IsSet)
                writer.WriteString("BuildVersion", tbioGame.BuildVersion);

            if (tbioGame.GameModeOption.IsSet)
                writer.WriteString("GameMode", tbioGame.GameMode);

            if (tbioGame.PlayerUserIdsOption.IsSet)
            {
                writer.WritePropertyName("PlayerUserIds");
                JsonSerializer.Serialize(writer, tbioGame.PlayerUserIds, jsonSerializerOptions);
            }
            if (tbioGame.RunTimeOption.IsSet)
                writer.WriteNumber("RunTime", tbioGame.RunTimeOption.Value!.Value);

            if (tbioGame.GameServerStateOption.IsSet)
                writer.WriteNumber("GameServerState", tbioGame.GameServerStateOption.Value!.Value);

            if (tbioGame.TagsOption.IsSet)
            {
                writer.WritePropertyName("Tags");
                JsonSerializer.Serialize(writer, tbioGame.Tags, jsonSerializerOptions);
            }
            if (tbioGame.LastHeartbeatOption.IsSet)
                writer.WriteNumber("LastHeartbeat", tbioGame.LastHeartbeatOption.Value!.Value);

            if (tbioGame.ServerHostnameOption.IsSet)
                writer.WriteString("ServerHostname", tbioGame.ServerHostname);

            if (tbioGame.ServerIPV4AddressOption.IsSet)
                writer.WriteString("ServerIPV4Address", tbioGame.ServerIPV4Address);

            if (tbioGame.ServerPortOption.IsSet)
                writer.WriteNumber("ServerPort", tbioGame.ServerPortOption.Value!.Value);
        }
    }

    /// <summary>
    /// The TbioGameSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(TbioGame))]
    public partial class TbioGameSerializationContext : JsonSerializerContext { }
}
