// <auto-generated>
/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Unchained.ServerBrowser.Client;

namespace Unchained.ServerBrowser.Model
{
    /// <summary>
    /// UpdateResponse
    /// </summary>
    public partial class UpdateResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateResponse" /> class.
        /// </summary>
        /// <param name="refreshBefore">Unix timestamp for when the server should refresh its registration. Only present if operation was successful</param>
        /// <param name="server">server</param>
        [JsonConstructor]
        public UpdateResponse(double refreshBefore, ServerResponse server)
        {
            RefreshBefore = refreshBefore;
            Server = server;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Unix timestamp for when the server should refresh its registration. Only present if operation was successful
        /// </summary>
        /// <value>Unix timestamp for when the server should refresh its registration. Only present if operation was successful</value>
        [JsonPropertyName("refresh_before")]
        public double RefreshBefore { get; set; }

        /// <summary>
        /// Gets or Sets Server
        /// </summary>
        [JsonPropertyName("server")]
        public ServerResponse Server { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateResponse {\n");
            sb.Append("  RefreshBefore: ").Append(RefreshBefore).Append("\n");
            sb.Append("  Server: ").Append(Server).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateResponse" />
    /// </summary>
    public class UpdateResponseJsonConverter : JsonConverter<UpdateResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="UpdateResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<double?> refreshBefore = default;
            Option<ServerResponse?> server = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "refresh_before":
                            refreshBefore = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "server":
                            server = new Option<ServerResponse?>(JsonSerializer.Deserialize<ServerResponse>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!refreshBefore.IsSet)
                throw new ArgumentException("Property is required for class UpdateResponse.", nameof(refreshBefore));

            if (!server.IsSet)
                throw new ArgumentException("Property is required for class UpdateResponse.", nameof(server));

            if (refreshBefore.IsSet && refreshBefore.Value == null)
                throw new ArgumentNullException(nameof(refreshBefore), "Property is not nullable for class UpdateResponse.");

            if (server.IsSet && server.Value == null)
                throw new ArgumentNullException(nameof(server), "Property is not nullable for class UpdateResponse.");

            return new UpdateResponse(refreshBefore.Value!.Value!, server.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateResponse updateResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateResponse updateResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateResponse.Server == null)
                throw new ArgumentNullException(nameof(updateResponse.Server), "Property is required for class UpdateResponse.");

            writer.WriteNumber("refresh_before", updateResponse.RefreshBefore);

            writer.WritePropertyName("server");
            JsonSerializer.Serialize(writer, updateResponse.Server, jsonSerializerOptions);
        }
    }

    /// <summary>
    /// The UpdateResponseSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(UpdateResponse))]
    public partial class UpdateResponseSerializationContext : JsonSerializerContext { }
}
