// <auto-generated>
/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Unchained.ServerBrowser.Client;

namespace Unchained.ServerBrowser.Model
{
    /// <summary>
    /// UpdateRegisteredServer
    /// </summary>
    public partial class UpdateRegisteredServer : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateRegisteredServer" /> class.
        /// </summary>
        /// <param name="playerCount">The number of players currently on the server</param>
        /// <param name="maxPlayers">The max number of players the server allows</param>
        /// <param name="currentMap">The current map being played on the server</param>
        [JsonConstructor]
        public UpdateRegisteredServer(int playerCount, int maxPlayers, string currentMap)
        {
            PlayerCount = playerCount;
            MaxPlayers = maxPlayers;
            CurrentMap = currentMap;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The number of players currently on the server
        /// </summary>
        /// <value>The number of players currently on the server</value>
        [JsonPropertyName("player_count")]
        public int PlayerCount { get; set; }

        /// <summary>
        /// The max number of players the server allows
        /// </summary>
        /// <value>The max number of players the server allows</value>
        [JsonPropertyName("max_players")]
        public int MaxPlayers { get; set; }

        /// <summary>
        /// The current map being played on the server
        /// </summary>
        /// <value>The current map being played on the server</value>
        [JsonPropertyName("current_map")]
        public string CurrentMap { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateRegisteredServer {\n");
            sb.Append("  PlayerCount: ").Append(PlayerCount).Append("\n");
            sb.Append("  MaxPlayers: ").Append(MaxPlayers).Append("\n");
            sb.Append("  CurrentMap: ").Append(CurrentMap).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateRegisteredServer" />
    /// </summary>
    public class UpdateRegisteredServerJsonConverter : JsonConverter<UpdateRegisteredServer>
    {
        /// <summary>
        /// Deserializes json to <see cref="UpdateRegisteredServer" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateRegisteredServer Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> playerCount = default;
            Option<int?> maxPlayers = default;
            Option<string?> currentMap = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "player_count":
                            playerCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "max_players":
                            maxPlayers = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "current_map":
                            currentMap = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!playerCount.IsSet)
                throw new ArgumentException("Property is required for class UpdateRegisteredServer.", nameof(playerCount));

            if (!maxPlayers.IsSet)
                throw new ArgumentException("Property is required for class UpdateRegisteredServer.", nameof(maxPlayers));

            if (!currentMap.IsSet)
                throw new ArgumentException("Property is required for class UpdateRegisteredServer.", nameof(currentMap));

            if (playerCount.IsSet && playerCount.Value == null)
                throw new ArgumentNullException(nameof(playerCount), "Property is not nullable for class UpdateRegisteredServer.");

            if (maxPlayers.IsSet && maxPlayers.Value == null)
                throw new ArgumentNullException(nameof(maxPlayers), "Property is not nullable for class UpdateRegisteredServer.");

            if (currentMap.IsSet && currentMap.Value == null)
                throw new ArgumentNullException(nameof(currentMap), "Property is not nullable for class UpdateRegisteredServer.");

            return new UpdateRegisteredServer(playerCount.Value!.Value!, maxPlayers.Value!.Value!, currentMap.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateRegisteredServer" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateRegisteredServer"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateRegisteredServer updateRegisteredServer, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateRegisteredServer, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateRegisteredServer" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateRegisteredServer"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateRegisteredServer updateRegisteredServer, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateRegisteredServer.CurrentMap == null)
                throw new ArgumentNullException(nameof(updateRegisteredServer.CurrentMap), "Property is required for class UpdateRegisteredServer.");

            writer.WriteNumber("player_count", updateRegisteredServer.PlayerCount);

            writer.WriteNumber("max_players", updateRegisteredServer.MaxPlayers);

            writer.WriteString("current_map", updateRegisteredServer.CurrentMap);
        }
    }

    /// <summary>
    /// The UpdateRegisteredServerSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(UpdateRegisteredServer))]
    public partial class UpdateRegisteredServerSerializationContext : JsonSerializerContext { }
}
