// <auto-generated>
/*
 * Server Browser API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using Unchained.ServerBrowser.Client;

namespace Unchained.ServerBrowser.Model
{
    /// <summary>
    /// VerifiedListResponse
    /// </summary>
    public partial class VerifiedListResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VerifiedListResponse" /> class.
        /// </summary>
        /// <param name="verifiedIps">verifiedIps</param>
        [JsonConstructor]
        public VerifiedListResponse(List<string> verifiedIps)
        {
            VerifiedIps = verifiedIps;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets VerifiedIps
        /// </summary>
        [JsonPropertyName("verified_ips")]
        public List<string> VerifiedIps { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VerifiedListResponse {\n");
            sb.Append("  VerifiedIps: ").Append(VerifiedIps).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="VerifiedListResponse" />
    /// </summary>
    public class VerifiedListResponseJsonConverter : JsonConverter<VerifiedListResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="VerifiedListResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override VerifiedListResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<string>?> verifiedIps = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "verified_ips":
                            verifiedIps = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!verifiedIps.IsSet)
                throw new ArgumentException("Property is required for class VerifiedListResponse.", nameof(verifiedIps));

            if (verifiedIps.IsSet && verifiedIps.Value == null)
                throw new ArgumentNullException(nameof(verifiedIps), "Property is not nullable for class VerifiedListResponse.");

            return new VerifiedListResponse(verifiedIps.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="VerifiedListResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="verifiedListResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, VerifiedListResponse verifiedListResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, verifiedListResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="VerifiedListResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="verifiedListResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, VerifiedListResponse verifiedListResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (verifiedListResponse.VerifiedIps == null)
                throw new ArgumentNullException(nameof(verifiedListResponse.VerifiedIps), "Property is required for class VerifiedListResponse.");

            writer.WritePropertyName("verified_ips");
            JsonSerializer.Serialize(writer, verifiedListResponse.VerifiedIps, jsonSerializerOptions);
        }
    }

    /// <summary>
    /// The VerifiedListResponseSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(VerifiedListResponse))]
    public partial class VerifiedListResponseSerializationContext : JsonSerializerContext { }
}
