using UnchainedLauncher.Core.JsonModels.Metadata.V3;
using UnchainedLauncher.UnrealModScanner.Models; // Now accessible!

namespace UnrealModScanner.Services;

public static class V3MetadataGenerator {
    public static Release CreateRelease(PakInventoryDto pak, string repoUrl, string scannerVersion) {
        // 1. Extract metadata from the first blueprint found in the pak
        // fall back to pak name if no blueprint exists
        var bp = pak.Inventory.Blueprints.FirstOrDefault()
                 ?? new BlueprintDto { ModName = pak.PakName, Author = "Unknown" };

        // 2. Map scanner data to the Launcher's V3 Manifest format
        var manifest = new ModManifest(
            RepoUrl: repoUrl,
            Name: pak.PakName.Split(".").First(),
            Description: $"Auto-generated by ModScanner v{scannerVersion}",
            HomePage: repoUrl,
            ImageUrl: null,
            ModType: bp.IsClientSide ? ModType.Client : ModType.Shared,
            Authors: new List<string> { bp.Author },
            Dependencies: new List<Dependency>(),
            Tags: MapInventoryToTags(pak.Inventory),
            Maps: pak.Inventory.Maps.Select(m => System.IO.Path.GetFileNameWithoutExtension(m.Path)).ToList(),
            OptionFlags: new OptionFlags(ActorMod: pak.Inventory.Markers.Any())
        );

        // 3. Return the Release record for the Registry
        return new Release(
            Tag: string.IsNullOrWhiteSpace(bp.Version) ? "v1.0.0" : FixVersion(bp.Version),
            ReleaseHash: pak.PakHash ?? "0",
            PakFileName: pak.PakName,
            ReleaseDate: DateTime.UtcNow,
            Manifest: manifest,
            ReleaseNotesMarkdown: $"Scanner session: {DateTime.Now:yyyy-MM-dd}"
        );
    }

    private static List<ModTag> MapInventoryToTags(AssetCollections inventory) {
        var tags = new List<ModTag>();
        if (inventory.Maps.Any()) tags.Add(ModTag.Map);
        if (inventory.Replacements.Any()) tags.Add(ModTag.Cosmetic);
        return tags;
    }

    private static string FixVersion(string v) => v.StartsWith("v") ? v : $"v{v}";
}